#include "image/ImageEditorWindow.h"
#include "image/ImageEditorCanvas.h"
#include "image/ImageAdjustments.h"
#include "image/ImageHdr.h"
#include "image/ImagePsd.h"
#include "player/PlayerImage.h"
#include <QActionGroup>
#include <QApplication>
#include <QClipboard>
#include <QMimeData>
#include <QCloseEvent>
#include <QCheckBox>
#include <QColorDialog>
#include <QComboBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDockWidget>
#include <QDoubleSpinBox>
#include <QFileDialog>
#include <QFileInfo>
#include <QFontComboBox>
#include <QFormLayout>
#include <QGridLayout>
#include <QInputDialog>
#include <QLabel>
#include <QLineEdit>
#include <QPlainTextEdit>
#include <QMenuBar>
#include <QMessageBox>
#include <QMouseEvent>
#include <QPainter>
#include <QPalette>
#include <QPushButton>
#include <QPointer>
#include <QSignalBlocker>
#include <QSpinBox>
#include <QStackedWidget>
#include <QStatusBar>
#include <QTabBar>
#include <QTabWidget>
#include <QTableWidget>
#include <QThread>
#include <QTimer>
#include <QToolBar>
#include <QToolButton>
#include <QTreeWidget>
#include <QUndoView>
#include <QVBoxLayout>
#include <algorithm>
#include <cmath>
#include <functional>

namespace vsr {
namespace {
class NativeImageClipboard final : public QMimeData {
public:
    QImage pixels;
    QPoint origin;
};
ImagePrecision precisionFor(const QImage &image) {
    if(image.format()==QImage::Format_RGBA32FPx4 || image.format()==QImage::Format_RGBA32FPx4_Premultiplied || image.format()==QImage::Format_RGBX32FPx4 || image.format()==QImage::Format_RGBA16FPx4 || image.format()==QImage::Format_RGBA16FPx4_Premultiplied || image.format()==QImage::Format_RGBX16FPx4)return ImagePrecision::Float32;
    return image.depth()>32 || image.format()==QImage::Format_Grayscale16?ImagePrecision::UInt16:ImagePrecision::UInt8;
}
ImageLayerInfo activeLayer(ImageDocument *doc,const QUuid &id){for(const auto &layer:doc->layers())if(layer.id==id)return layer;return {};}
QIcon toolIcon(const QString &kind) {
    QPixmap pixmap(24,24);pixmap.fill(Qt::transparent);QPainter p(&pixmap);p.setRenderHint(QPainter::Antialiasing);p.setPen(QPen(QColor("#ddd"),1.6));
    if(kind=="move"){p.drawLine(12,2,12,22);p.drawLine(2,12,22,12);p.drawPolyline(QPolygonF{{8,6},{12,2},{16,6}});p.drawPolyline(QPolygonF{{8,18},{12,22},{16,18}});p.drawPolyline(QPolygonF{{6,8},{2,12},{6,16}});p.drawPolyline(QPolygonF{{18,8},{22,12},{18,16}});}
    else if(kind=="select" || kind=="ellipseSelect"){p.setPen(QPen(QColor("#ddd"),1.6,Qt::DashLine));if(kind=="select")p.drawRect(4,4,16,16);else p.drawEllipse(3,5,18,14);}
    else if(kind=="polygon"){p.setPen(QPen(QColor("#ddd"),1.6,Qt::DashLine));p.drawPolygon(QPolygonF{{3,19},{8,3},{21,9},{16,21}});}
    else if(kind=="magnetic"){p.drawArc(4,3,16,16,0,180*16);p.drawLine(4,11,4,20);p.drawLine(20,11,20,20);p.drawLine(3,16,7,16);p.drawLine(17,16,21,16);}
    else if(kind=="quick"){p.setPen(QPen(QColor("#ddd"),1.6,Qt::DashLine));p.drawEllipse(3,3,13,13);p.setPen(QPen(QColor("#ddd"),2));p.drawLine(12,19,22,6);}
    else if(kind=="object"){p.setPen(QPen(QColor("#ddd"),1.6,Qt::DashLine));p.drawRect(3,3,18,18);p.setBrush(QColor("#ddd"));p.drawPolygon(QPolygonF{{8,7},{8,18},{11,15},{14,20},{17,18},{14,13},{18,13}});}
    else if(kind=="ruler"){p.drawRect(2,7,20,10);for(int x=5;x<22;x+=4)p.drawLine(x,7,x,12);}
    else if(kind=="slice"){p.drawLine(3,20,20,3);p.drawEllipse(2,13,7,7);p.drawEllipse(10,15,7,7);}
    else if(kind=="replace"){p.drawEllipse(2,2,10,10);p.setBrush(QColor("#ddd"));p.drawRect(14,14,8,8);p.drawLine(6,19,18,6);}
    else if(kind=="fill"){p.drawPolygon(QPolygonF{{3,12},{11,3},{20,12},{12,21}});p.drawLine(3,12,20,12);p.drawEllipse(19,17,3,5);}
    else if(kind=="sharpen")p.drawPolygon(QPolygonF{{12,3},{3,21},{21,21}});
    else if(kind=="burn"){p.setBrush(QColor("#ddd"));p.drawEllipse(4,4,15,15);p.drawLine(17,17,22,22);}
    else if(kind=="sponge"){p.drawRect(3,6,18,13);for(int x=6;x<20;x+=4){p.drawPoint(x,10);p.drawPoint(x,15);}}
    else if(kind=="lasso"){p.drawEllipse(3,4,18,12);p.drawArc(7,11,8,12,180*16,180*16);}
    else if(kind=="wand"){p.drawLine(5,21,18,8);p.drawLine(17,2,17,6);p.drawLine(21,6,23,6);p.drawLine(9,4,12,7);p.drawLine(21,10,23,12);}
    else if(kind=="crop"){p.drawPolyline(QPolygonF{{6,2},{6,18},{22,18}});p.drawPolyline(QPolygonF{{2,6},{18,6},{18,22}});}
    else if(kind=="dropper"){p.drawPolygon(QPolygonF{{3,21},{6,15},{17,4},{20,7},{9,18}});p.drawLine(14,4,20,10);}
    else if(kind=="heal"){p.translate(12,12);p.rotate(-40);p.drawRoundedRect(-4,-10,8,20,3,3);p.drawLine(-4,-3,4,-3);p.drawLine(-4,3,4,3);}
    else if(kind=="brush"){p.drawPolygon(QPolygonF{{8,16},{17,3},{21,5},{12,19}});p.setBrush(QColor("#ddd"));QPainterPath v;v.moveTo(9,15);v.cubicTo(1,13,6,21,2,22);v.cubicTo(12,23,13,19,9,15);p.drawPath(v);}
    else if(kind=="stamp"){p.drawRect(4,17,16,4);p.drawPolyline(QPolygonF{{6,17},{8,13},{8,7},{10,3},{14,3},{16,7},{16,13},{18,17}});}
    else if(kind=="eraser")p.drawPolygon(QPolygonF{{3,15},{13,4},{22,12},{12,21},{8,21}});
    else if(kind=="gradient"){QLinearGradient g(3,0,21,0);g.setColorAt(0,Qt::white);g.setColorAt(1,Qt::black);p.fillRect(3,5,18,14,g);p.drawRect(3,5,18,14);}
    else if(kind=="blur"){QPainterPath v;v.moveTo(12,2);v.cubicTo(8,9,3,12,5,18);v.cubicTo(7,25,22,22,19,14);v.closeSubpath();p.drawPath(v);}
    else if(kind=="dodge"){p.drawEllipse(10,3,11,11);p.drawLine(4,22,14,12);}
    else if(kind=="pen"){p.drawPolygon(QPolygonF{{3,21},{7,6},{19,3},{22,15}});p.drawLine(3,21,13,11);p.drawEllipse(11,9,4,4);}
    else if(kind=="text"){QFont f=p.font();f.setPixelSize(23);f.setBold(true);p.setFont(f);p.drawText(pixmap.rect(),Qt::AlignCenter,"T");}
    else if(kind=="shape")p.drawRect(4,4,16,16);
    else if(kind=="ellipseShape")p.drawEllipse(3,5,18,14);
    else if(kind=="hand")p.drawPolyline(QPolygonF{{5,20},{2,12},{5,10},{8,14},{8,5},{11,4},{12,11},{12,2},{15,2},{15,11},{16,4},{19,5},{19,13},{20,8},{23,10},{22,17},{18,22},{9,22},{5,20}});
    else if(kind=="zoom"){p.drawEllipse(3,3,13,13);p.drawLine(14,14,22,22);}
    else if(kind=="history"){p.drawArc(3,3,18,18,30*16,290*16);p.drawPolyline(QPolygonF{{3,4},{3,11},{10,11}});p.drawLine(12,6,12,12);p.drawLine(12,12,17,15);}
    return QIcon(pixmap);
}
class EditorToolButton final : public QToolButton {
public:
    explicit EditorToolButton(QWidget *parent):QToolButton(parent){}
protected:
    void mousePressEvent(QMouseEvent *event) override {
        if(menu() && event->button()==Qt::LeftButton && event->position().x()>=width()-12 && event->position().y()>=height()-11){menu()->exec(mapToGlobal(QPoint(width(),height())));event->accept();return;}
        QToolButton::mousePressEvent(event);
    }
};
class EditorRuler final : public QWidget {
public:
    EditorRuler(ImageEditorCanvas *canvas,bool vertical,QWidget *parent):QWidget(parent),canvas_(canvas),vertical_(vertical){if(vertical)setFixedWidth(22);else setFixedHeight(22);setProperty("cursorVisible",false);connect(canvas,&ImageEditorCanvas::viewChanged,this,qOverload<>(&QWidget::update));connect(canvas,&ImageEditorCanvas::cursorPositionChanged,this,[this](QPointF point,bool visible){cursor_=vertical_?point.y():point.x();cursorVisible_=visible;setProperty("cursorValue",cursor_);setProperty("cursorVisible",visible);update();});}
protected:
    void paintEvent(QPaintEvent *) override {
        QPainter p(this);p.fillRect(rect(),QColor("#383838"));p.setPen(QColor("#bbb"));QFont f=p.font();f.setPixelSize(9);p.setFont(f);const auto start=canvas_->documentPoint({0,0});const double zoom=canvas_->zoom();double step=std::pow(10.,std::floor(std::log10(std::max(1.,70/zoom))));if(step*zoom<35)step*=5;else if(step*zoom<65)step*=2;const double first=vertical_?start.y():start.x();const int length=vertical_?height():width();
        for(double value=std::floor(first/step)*step;value<=first+length/zoom;value+=step){const int at=qRound((value-first)*zoom);if(vertical_){p.drawLine(12,at,21,at);p.save();p.translate(11,at+3);p.rotate(-90);p.drawText(0,0,QString::number(value,'f',0));p.restore();}else{p.drawLine(at,13,at,21);p.drawText(at+3,11,QString::number(value,'f',0));}for(int i=1;i<5;++i){const int sub=at+qRound(i*step*zoom/5);if(vertical_)p.drawLine(17,sub,21,sub);else p.drawLine(sub,17,sub,21);}}
        if(cursorVisible_){const int at=qRound((cursor_-first)*zoom);p.setPen(QColor("#eee"));if(vertical_){p.drawLine(0,at,width(),at);p.setBrush(QColor("#eee"));p.drawPolygon(QPolygonF{{21.,double(at)},{16.,double(at-4)},{16.,double(at+4)}});}else{p.drawLine(at,0,at,height());p.setBrush(QColor("#eee"));p.drawPolygon(QPolygonF{{double(at),21.},{double(at-4),16.},{double(at+4),16.}});}}
    }
private: ImageEditorCanvas *canvas_;bool vertical_;double cursor_=0;bool cursorVisible_=false;
};
class BlendRangeSlider final : public QWidget {
public:
    BlendRangeSlider(QWidget *parent,std::function<void(ImageBlendRange)> changed):QWidget(parent),changed_(std::move(changed)){setMinimumHeight(40);setMinimumWidth(320);setToolTip(QObject::tr("拖动黑白端点；Alt 拖动拆分端点，设置渐变过渡。"));}
    void setRange(ImageBlendRange range){range_=range;update();}
protected:
    void paintEvent(QPaintEvent *) override{QPainter p(this);const QRect bar(8,4,width()-16,16);QLinearGradient g(bar.left(),0,bar.right(),0);g.setColorAt(0,Qt::black);g.setColorAt(1,Qt::white);p.fillRect(bar,g);p.setPen(QColor("#999"));p.drawRect(bar);for(int i=0;i<4;++i){const double x=8+range_[i]*(width()-16);p.setBrush(i<2?QColor("#222"):QColor("#eee"));const double y=i%2?32:24;p.drawPolygon(QPolygonF{{x,y-4},{x-5,y+4},{x+5,y+4}});}}
    void mousePressEvent(QMouseEvent *e) override{if(e->button()!=Qt::LeftButton)return;const double position=std::clamp((e->position().x()-8)/(width()-16),0.,1.);handle_=0;for(int i=1;i<4;++i)if(std::abs(range_[i]-position)<std::abs(range_[handle_]-position))handle_=i;paired_=!e->modifiers().testFlag(Qt::AltModifier);if(!paired_&&range_[0]==range_[1]&&handle_<2)handle_=1;else if(!paired_&&range_[2]==range_[3]&&handle_>=2)handle_=2;drag(e->position());}
    void mouseMoveEvent(QMouseEvent *e) override{if(e->buttons().testFlag(Qt::LeftButton)&&handle_>=0)drag(e->position());}
    void mouseReleaseEvent(QMouseEvent *) override{handle_=-1;}
private:
    void drag(QPointF point){const float value=float(std::clamp((point.x()-8)/(width()-16),0.,1.));if(paired_){const int begin=handle_<2?0:2;const float delta=value-range_[handle_];const float shift=std::clamp(delta,begin==0?-range_[0]:range_[1]-range_[2],begin==0?range_[2]-range_[1]:1-range_[3]);range_[begin]+=shift;range_[begin+1]+=shift;}else range_[handle_]=std::clamp(value,handle_?range_[handle_-1]:0.f,handle_<3?range_[handle_+1]:1.f);changed_(range_);update();}
    ImageBlendRange range_{0,0,1,1};std::function<void(ImageBlendRange)> changed_;int handle_=-1;bool paired_=true;
};
class EditorColorField final : public QWidget {
public:
    EditorColorField(QWidget *parent,std::function<void(QColor)> changed):QWidget(parent),changed_(std::move(changed)){setMinimumHeight(150);}
    void setColor(QColor value){color_=value;update();}
protected:
    void paintEvent(QPaintEvent *) override{QPainter p(this);const QRect field(0,0,width()-23,height());p.fillRect(field,QColor::fromHsvF(std::max(0.,double(color_.hsvHueF())),1,1));QLinearGradient w(0,0,field.width(),0);w.setColorAt(0,Qt::white);w.setColorAt(1,Qt::transparent);p.fillRect(field,w);QLinearGradient b(0,0,0,height());b.setColorAt(0,Qt::transparent);b.setColorAt(1,Qt::black);p.fillRect(field,b);for(int y=0;y<height();++y)p.fillRect(QRect(width()-17,y,17,1),QColor::fromHsvF(double(y)/height(),1,1));const QPointF at(color_.hsvSaturationF()*field.width(),(1-color_.valueF())*height());p.setPen(QPen(Qt::black,2));p.drawEllipse(at,4,4);p.setPen(Qt::white);p.drawEllipse(at,3,3);}
    void mousePressEvent(QMouseEvent *e) override{pick(e->position());}
    void mouseMoveEvent(QMouseEvent *e) override{if(e->buttons().testFlag(Qt::LeftButton))pick(e->position());}
private:
    void pick(QPointF at){const bool hue=at.x()>width()-22;color_=QColor::fromHsvF(hue?std::clamp(at.y()/height(),0.,.999999):std::max(0.,double(color_.hsvHueF())),hue?color_.hsvSaturationF():std::clamp(at.x()/std::max(1,width()-23),0.,1.),hue?color_.valueF():std::clamp(1-at.y()/height(),0.,1.));changed_(color_);update();}
    QColor color_=Qt::black;std::function<void(QColor)> changed_;
};
QWidget *optionGroup(QToolBar *bar){auto *w=new QWidget(bar);auto *l=new QHBoxLayout(w);l->setContentsMargins(0,0,0,0);l->setSpacing(5);bar->addWidget(w);return w;}
}
ImageEditorWindow::ImageEditorWindow(const QImage &image,const QString &sourcePath,QWidget *parent):QMainWindow(parent),sourcePath_(sourcePath){document_=new ImageDocument(image.size(),precisionFor(image),this);document_->setColorSpace(image.colorSpace());document_->setMetadata("sourcePath",sourcePath);const auto id=document_->addLayer(tr("背景"),image);auto layer=activeLayer(document_,id);layer.locked=true;document_->updateLayer(layer);document_->history()->clear();document_->history()->setClean();buildUi();}
ImageEditorWindow::ImageEditorWindow(ImageDocument *document,const QString &sourcePath,QWidget *parent):QMainWindow(parent),document_(document),sourcePath_(sourcePath){document_->setParent(this);buildUi();}
ImageEditorWindow::~ImageEditorWindow(){for(const auto &page:pages_){disconnect(page.document,nullptr,this,nullptr);disconnect(page.document->history(),nullptr,this,nullptr);disconnect(page.tools,nullptr,this,nullptr);disconnect(page.canvas,nullptr,this,nullptr);}}
void ImageEditorWindow::buildUi(){
    setObjectName("imageEditorWindow");setAttribute(Qt::WA_DeleteOnClose);resize(1440,960);setWindowTitle(tr("图像编辑 · %1[*]").arg(QFileInfo(sourcePath_).fileName()));
    QPalette editorPalette;for(auto state:{QPalette::Active,QPalette::Inactive,QPalette::Disabled}){editorPalette.setColor(state,QPalette::Window,QColor("#383838"));editorPalette.setColor(state,QPalette::Base,QColor("#383838"));editorPalette.setColor(state,QPalette::AlternateBase,QColor("#383838"));editorPalette.setColor(state,QPalette::Button,QColor("#383838"));editorPalette.setColor(state,QPalette::WindowText,QColor("#ddd"));editorPalette.setColor(state,QPalette::Text,QColor("#ddd"));editorPalette.setColor(state,QPalette::ButtonText,QColor("#ddd"));editorPalette.setColor(state,QPalette::Highlight,QColor("#606060"));editorPalette.setColor(state,QPalette::HighlightedText,Qt::white);editorPalette.setColor(state,QPalette::ToolTipBase,QColor("#383838"));editorPalette.setColor(state,QPalette::ToolTipText,QColor("#eee"));editorPalette.setColor(state,QPalette::PlaceholderText,QColor("#999"));editorPalette.setColor(state,QPalette::Light,QColor("#626262"));editorPalette.setColor(state,QPalette::Dark,QColor("#262626"));}setPalette(editorPalette);setAttribute(Qt::WA_WindowPropagation,true);
    setStyleSheet("QWidget{background:#383838;color:#ddd;}QMenu::item:selected{background:#606060;}QToolBar{border:0;spacing:2px;}QToolButton{border:1px solid transparent;padding:4px;}QToolButton:hover,QToolButton:checked{background:#505050;border-color:#707070;}QTabBar::tab{background:#383838;color:#bbb;padding:6px 10px;}QTabBar::tab:selected{background:#454545;color:white;}QDockWidget::title{padding:3px;background:#383838;}QAbstractScrollArea,QTreeWidget,QListView,QTableWidget{background:#383838;border:1px solid #292929;}QTreeWidget::item{height:28px;}QTreeWidget::item:selected{background:#606060;}QComboBox,QSpinBox,QDoubleSpinBox,QLineEdit{background:#383838;border:1px solid #272727;padding:3px;}QComboBox QAbstractItemView{background:#383838;selection-background-color:#606060;}QPushButton{background:#383838;border:1px solid #292929;padding:4px 7px;}QPushButton:hover{background:#535353;}QTabWidget::pane{background:#383838;border:1px solid #292929;}QHeaderView::section{background:#383838;color:#ddd;border:1px solid #292929;}QScrollBar{background:#383838;}QScrollBar:vertical{width:13px;}QScrollBar:horizontal{height:13px;}QScrollBar::handle{background:#606060;min-width:18px;min-height:18px;}QScrollBar::add-page,QScrollBar::sub-page{background:#383838;}QScrollBar::add-line,QScrollBar::sub-line{background:#383838;}");
    tools_=new ImageEditorTools(document_,this);const auto original=document_->layers();for(auto i=original.crbegin();i!=original.crend();++i)if(!i->group && !i->locked){tools_->setLayer(i->id);break;}canvas_=new ImageEditorCanvas(tools_,this);
    pages_.append({document_,tools_,canvas_,sourcePath_});
    auto *center=new QWidget(this);auto *layout=new QVBoxLayout(center);layout->setContentsMargins(0,0,0,0);layout->setSpacing(0);documentTab_=new QTabBar(center);documentTab_->setObjectName("imageEditorDocumentTabs");documentTab_->setExpanding(false);documentTab_->setElideMode(Qt::ElideMiddle);documentTab_->setTabsClosable(true);documentTab_->addTab(QFileInfo(sourcePath_).fileName());layout->addWidget(documentTab_);pagesStack_=new QStackedWidget(center);pagesStack_->setObjectName("imageEditorDocumentStack");pagesStack_->addWidget(makePage(canvas_));layout->addWidget(pagesStack_,1);setCentralWidget(center);connect(documentTab_,&QTabBar::currentChanged,this,&ImageEditorWindow::activateDocument);connect(documentTab_,&QTabBar::tabCloseRequested,this,&ImageEditorWindow::closeDocument);
    auto action=[this](QMenu *menu,const QString &name,const QString &object,QKeySequence key,std::function<void()> fn){auto *a=menu->addAction(name);a->setObjectName(object);if(!key.isEmpty())a->setShortcut(key);connect(a,&QAction::triggered,this,std::move(fn));return a;};
    auto *file=menuBar()->addMenu(tr("文件(F)"));action(file,tr("新建…"),"imageEditorNew",QKeySequence::New,[this]{newImage();});action(file,tr("打开…"),"imageEditorOpen",QKeySequence::Open,[this]{openImage();});file->addSeparator();
    action(file,tr("另存 PSD/PSB 图层工程…"),"imageEditorSavePsd",QKeySequence::Save,[this]{exportDocument(false);});action(file,tr("导出 PNG…"),"imageEditorSavePng",QKeySequence::SaveAs,[this]{savePng();});action(file,tr("导出浮点 TIFF(扁平)…"),"imageEditorExportFloat",{},[this]{exportDocument(true);});file->addSeparator();action(file,tr("关闭"),"imageEditorClose",QKeySequence::Close,[this]{closeDocument(activePage_);});
    auto *edit=menuBar()->addMenu(tr("编辑(E)"));auto *undo=action(edit,tr("撤销"),"imageEditorUndo",QKeySequence::Undo,[this]{canvas_->cancelGesture();document_->history()->undo();});auto *redo=action(edit,tr("重做"),"imageEditorRedo",QKeySequence::Redo,[this]{canvas_->cancelGesture();document_->history()->redo();});undo->setEnabled(document_->history()->canUndo());redo->setEnabled(document_->history()->canRedo());edit->addSeparator();
    auto *freeTransform=action(edit,tr("自由变换"),"imageEditorFreeTransform",QKeySequence("Ctrl+T"),[this]{setEditorTool(int(ImageEditorTool::Move));canvas_->startFreeTransform();updateProperties();});auto *transforms=edit->addMenu(tr("变换"));
    for(const auto &[name,horizontal]:QList<QPair<QString,bool>>{{tr("水平翻转"),true},{tr("垂直翻转"),false}})action(transforms,name,horizontal?"imageEditorFlipHorizontal":"imageEditorFlipVertical",{},[this,horizontal]{canvas_->cancelGesture();QString error;if(!document_->flipLayer(tools_->layer(),horizontal,&error))QMessageBox::warning(this,tr("图层翻转"),error);});
    for(const auto &[name,turns]:QList<QPair<QString,int>>{{tr("顺时针 90°"),1},{tr("逆时针 90°"),-1},{tr("旋转 180°"),2}})action(transforms,name,turns==1?"imageEditorRotateRight":turns==-1?"imageEditorRotateLeft":"imageEditorRotate180",{},[this,turns]{canvas_->cancelGesture();QString error;if(!document_->rotateLayer(tools_->layer(),turns,&error))QMessageBox::warning(this,tr("图层旋转"),error);});edit->addSeparator();
    action(edit,tr("复制选区 / 当前图层"),"imageEditorCopy",QKeySequence::Copy,[this]{QPoint origin;const auto pixels=tools_->selectedPixels(&origin);if(pixels.isNull()){QMessageBox::warning(this,tr("复制"),tr("选区为空或超过 16M 像素，请缩小选区或使用文件导出。"));return;}auto *data=new NativeImageClipboard;data->pixels=pixels;data->origin=origin;data->setImageData(ImageHdr::preview(pixels));QApplication::clipboard()->setMimeData(data);});
    action(edit,tr("粘贴为图层"),"imageEditorPaste",QKeySequence::Paste,[this]{const auto *native=dynamic_cast<const NativeImageClipboard *>(QApplication::clipboard()->mimeData());const auto image=native?native->pixels:QApplication::clipboard()->image();if(!image.isNull()){document_->beginEdit(tr("粘贴图层"));const auto id=document_->addLayer(tr("粘贴图层"),image,native?native->origin:QPoint());document_->clearSelection();document_->commitEdit();tools_->setLayer(id);rebuildLayers();}});
    action(edit,tr("通过复制的图层"),"imageEditorLayerCopy",QKeySequence("Ctrl+J"),[this]{tools_->layerFromSelection(false);});
    action(edit,tr("通过剪切的图层"),"imageEditorLayerCut",QKeySequence("Ctrl+Shift+J"),[this]{tools_->layerFromSelection(true);});
    action(edit,tr("填充前景色"),"imageEditorFill",QKeySequence("Alt+Backspace"),[this]{tools_->fillSelection();});action(edit,tr("设置历史画笔源"),"imageEditorHistorySource",{},[this]{tools_->captureHistorySource();});
    auto *image=menuBar()->addMenu(tr("图像(I)"));auto *adjust=image->addMenu(tr("调整"));const QStringList adjustmentNames{tr("曝光…"),tr("亮度 / 对比度…"),tr("色阶…"),tr("曲线…"),tr("色相 / 饱和度…"),tr("色彩平衡…"),tr("通道混合器…"),tr("反相"),tr("灰度"),tr("阈值…"),tr("色调分离…")};for(int i=0;i<adjustmentNames.size();++i)action(adjust,adjustmentNames[i],"imageEditorAdjustment_"+QString::number(i),{},[this,i]{adjustImage(i);});
    auto *precision=image->addMenu(tr("模式 / 精度"));for(const auto &[name,value]:QList<QPair<QString,ImagePrecision>>{{tr("8 位 / 通道"),ImagePrecision::UInt8},{tr("16 位 / 通道"),ImagePrecision::UInt16},{tr("32 位浮点 / 通道(HDR)"),ImagePrecision::Float32}})action(precision,name,"imageEditorPrecision_"+QString::number(int(value)),{},[this,value]{canvas_->cancelGesture();if(value!=ImagePrecision::Float32 && document_->precision()==ImagePrecision::Float32 && QMessageBox::question(this,tr("转换精度"),tr("转换为整数将截断 HDR 超范围值。继续？"))!=QMessageBox::Yes)return;document_->convertPrecision(value);});
    auto *profiles=image->addMenu(tr("转换工作色彩空间"));for(const auto &[name,space]:QList<QPair<QString,QColorSpace::NamedColorSpace>>{{"sRGB",QColorSpace::SRgb},{"Linear sRGB",QColorSpace::SRgbLinear},{"Display P3",QColorSpace::DisplayP3},{"Adobe RGB",QColorSpace::AdobeRgb},{"ProPhoto RGB",QColorSpace::ProPhotoRgb}})action(profiles,name,"imageEditorProfile_"+name,{},[this,space]{canvas_->cancelGesture();QString error;if(!ImageAdjustments::convertColorSpace(document_,QColorSpace(space),&error))QMessageBox::warning(this,tr("色彩转换"),error);});
    action(image,tr("画布大小…"),"imageEditorCanvasSize",{},[this]{QDialog dialog(this);dialog.setAttribute(Qt::WA_WindowPropagation,true);dialog.setPalette(palette());dialog.setWindowTitle(tr("画布大小"));QFormLayout form(&dialog);QSpinBox w,h;w.setRange(1,1000000);h.setRange(1,1000000);w.setValue(document_->size().width());h.setValue(document_->size().height());form.addRow(tr("宽度(px)"),&w);form.addRow(tr("高度(px)"),&h);QDialogButtonBox buttons(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);form.addRow(&buttons);connect(&buttons,&QDialogButtonBox::accepted,&dialog,&QDialog::accept);connect(&buttons,&QDialogButtonBox::rejected,&dialog,&QDialog::reject);if(dialog.exec()==QDialog::Accepted){canvas_->cancelGesture();document_->resizeCanvas({w.value(),h.value()},{});canvas_->fitToWindow();}});
    auto *layer=menuBar()->addMenu(tr("图层(L)"));action(layer,tr("新建透明图层"),"imageEditorAddLayer",QKeySequence("Ctrl+Shift+N"),[this]{addLayer();});action(layer,tr("复制图层"),"imageEditorDuplicateLayer",QKeySequence("Ctrl+J"),[this]{duplicateLayer();});action(layer,tr("删除图层"),"imageEditorDeleteLayer",QKeySequence(Qt::Key_Delete),[this]{deleteLayer();});action(layer,tr("重命名…"),"imageEditorRenameLayer",{},[this]{renameLayer();});action(layer,tr("上移图层"),"imageEditorRaiseLayer",QKeySequence("Ctrl+]"),[this]{reorderLayer(1);});action(layer,tr("下移图层"),"imageEditorLowerLayer",QKeySequence("Ctrl+["),[this]{reorderLayer(-1);});action(layer,tr("显示 / 隐藏"),"imageEditorVisibility",{},[this]{auto l=activeLayer(document_,tools_->layer());if(l.id.isNull())return;l.visible=!l.visible;document_->updateLayer(l,tr("图层可见性"));});action(layer,tr("锁定 / 解锁"),"imageEditorLockLayer",{},[this]{auto l=activeLayer(document_,tools_->layer());if(l.id.isNull())return;l.locked=!l.locked;document_->updateLayer(l,tr("图层锁定"));});action(layer,tr("启用 / 停用蒙版"),"imageEditorMaskEnabled",{},[this]{auto l=activeLayer(document_,tools_->layer());if(l.id.isNull())return;l.maskEnabled=!l.maskEnabled;document_->updateLayer(l,tr("图层蒙版"));});
    action(layer,tr("新建图层组"),"imageEditorAddGroup",{},[this]{addGroup(false);});action(layer,tr("从当前图层建立组"),"imageEditorGroupLayer",QKeySequence("Ctrl+G"),[this]{addGroup(true);});action(layer,tr("快速导出图层 PNG…"),"imageEditorExportLayer",{},[this]{exportLayer();});action(layer,tr("混合选项…"),"imageEditorBlendingOptions",{},[this]{blendingOptions();});action(layer,tr("合并可见图层"),"imageEditorMergeVisible",QKeySequence("Ctrl+Shift+E"),[this]{mergeAll(false);});action(layer,tr("拼合图像"),"imageEditorFlatten",{},[this]{mergeAll(true);});
    layer->addSeparator();auto *mergeDown=action(layer,tr("向下合并"),"imageEditorMergeDown",QKeySequence("Ctrl+E"),[this]{mergeLayerDown();});
    auto *select=menuBar()->addMenu(tr("选择(S)"));action(select,tr("全部"),"imageEditorSelectAll",QKeySequence::SelectAll,[this]{selectAll();});action(select,tr("取消选择"),"imageEditorDeselect",QKeySequence("Ctrl+D"),[this]{canvas_->cancelGesture();document_->clearSelection();});action(select,tr("反向"),"imageEditorInvertSelection",QKeySequence("Ctrl+Shift+I"),[this]{canvas_->cancelGesture();tools_->invertSelection();});action(select,tr("羽化…"),"imageEditorFeatherSelection",{},[this]{bool ok;const int r=QInputDialog::getInt(this,tr("羽化"),tr("半径(px)"),3,1,128,1,&ok);if(ok)tools_->featherSelection(r);});
    auto *filter=menuBar()->addMenu(tr("滤镜(T)"));for(const auto &[name,kind]:QList<QPair<QString,ImageAdjustmentKind>>{{tr("高斯模糊…"),ImageAdjustmentKind::GaussianBlur},{tr("USM 锐化…"),ImageAdjustmentKind::UnsharpMask},{tr("中值降噪…"),ImageAdjustmentKind::Median},{tr("边缘检测"),ImageAdjustmentKind::EdgeDetect}})action(filter,name,"imageEditorAdjustment_"+QString::number(int(kind)),{},[this,kind]{adjustImage(int(kind));});
    auto *view=menuBar()->addMenu(tr("视图(V)"));action(view,tr("适合窗口"),"imageEditorFit",QKeySequence("Ctrl+0"),[this]{canvas_->fitToWindow();});action(view,tr("实际像素 100%"),"imageEditorActualSize",QKeySequence("Ctrl+1"),[this]{canvas_->actualSize();});auto *rulers=action(view,tr("标尺"),"imageEditorRulers",QKeySequence("Ctrl+R"),[]{});rulers->setCheckable(true);rulers->setChecked(true);connect(rulers,&QAction::toggled,this,[this](bool show){for(auto *r:pagesStack_->findChildren<QWidget *>())if(r->objectName()=="imageEditorHorizontalRuler"||r->objectName()=="imageEditorVerticalRuler")r->setVisible(show);});auto *pixels=action(view,tr("像素网格"),"imageEditorGrid",{},[]{});pixels->setCheckable(true);connect(pixels,&QAction::toggled,this,[this](bool show){for(const auto &page:pages_)page.canvas->setShowGrid(show);});
    auto *toneMap=action(view,tr("启用 HDR → SDR 显示映射"),"imageEditorHdrToneMap",{},[]{});toneMap->setCheckable(true);connect(toneMap,&QAction::toggled,this,[this](bool enabled){auto settings=canvas_->hdrPreviewSettings();settings.toneMap=enabled;canvas_->setHdrPreviewSettings(settings);});
    const auto sourceTransfer=document_->colorSpace().transferFunction();if(sourceTransfer==QColorSpace::TransferFunction::St2084 || sourceTransfer==QColorSpace::TransferFunction::Hlg){auto settings=canvas_->hdrPreviewSettings();settings.whitePoint=sourceTransfer==QColorSpace::TransferFunction::St2084?64:12;canvas_->setHdrPreviewSettings(settings);toneMap->setChecked(true);}
    auto *nativeHdr=action(view,tr("HDR 显示(Windows 自动检测)"),"imageEditorNativeHdr",{},[]{});nativeHdr->setCheckable(true);connect(nativeHdr,&QAction::triggered,this,[this,nativeHdr](bool requested){const bool enabled=canvas_->setNativeHdrEnabled(requested);nativeHdr->setChecked(canvas_->nativeHdrActive());updateStatus();if(requested&&!enabled)QMessageBox::information(this,tr("HDR 显示"),canvas_->nativeHdrStatus());});
    action(view,tr("HDR → SDR 显示映射…"),"imageEditorHdrPreview",{},[this,toneMap]{QDialog dialog(this);dialog.setAttribute(Qt::WA_WindowPropagation,true);dialog.setPalette(palette());dialog.setWindowTitle(tr("HDR 显示映射(不修改原始数据)"));QFormLayout form(&dialog);QDoubleSpinBox exposure,white;const auto prior=canvas_->hdrPreviewSettings();exposure.setRange(-20,20);exposure.setDecimals(2);exposure.setValue(prior.exposure);white.setRange(.01,10000);white.setDecimals(2);white.setValue(prior.whitePoint);form.addRow(tr("曝光(EV)"),&exposure);form.addRow(tr("白点"),&white);QDialogButtonBox buttons(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);form.addRow(&buttons);connect(&buttons,&QDialogButtonBox::accepted,&dialog,&QDialog::accept);connect(&buttons,&QDialogButtonBox::rejected,&dialog,&QDialog::reject);if(dialog.exec()==QDialog::Accepted){auto s=prior;s.exposure=exposure.value();s.whitePoint=white.value();s.toneMap=true;canvas_->setHdrPreviewSettings(s);toneMap->setChecked(true);}});
    auto *windowMenu=menuBar()->addMenu(tr("窗口(W)"));
    toolBar_=new QToolBar(tr("工具"),this);toolBar_->setObjectName("imageEditorToolBar");toolBar_->setMovable(false);toolBar_->setFloatable(false);toolBar_->setFixedWidth(42);toolBar_->setIconSize({24,24});addToolBar(Qt::LeftToolBarArea,toolBar_);auto *group=new QActionGroup(this);
    using Tool=ImageEditorTool;using ToolEntry=QPair<Tool,QString>;
    const QList<QPair<QString,QList<ToolEntry>>> groups{
        {"move",{{Tool::Move,tr("移动 (V)")}}},{"select",{{Tool::Rectangle,tr("矩形选框 (M)")},{Tool::Ellipse,tr("椭圆选框")}}},
        {"lasso",{{Tool::Lasso,tr("套索 (L)")},{Tool::Polygon,tr("多边形套索")},{Tool::MagneticLasso,tr("磁性套索")}}},
        {"wand",{{Tool::MagicWand,tr("魔棒 (W)")},{Tool::QuickSelection,tr("快速选择")},{Tool::ObjectSelection,tr("框选辅助分割")}}},
        {"crop",{{Tool::Crop,tr("裁剪 (C)")},{Tool::Slice,tr("切片")}}},{"dropper",{{Tool::Eyedropper,tr("吸管 (I)")},{Tool::Ruler,tr("标尺")}}},
        {"heal",{{Tool::Heal,tr("污点 / 源修复 (J)")}}},{"brush",{{Tool::Brush,tr("画笔 (B)")},{Tool::ColorReplace,tr("颜色替换")}}},
        {"stamp",{{Tool::Clone,tr("仿制图章 (S)")}}},{"history",{{Tool::HistoryBrush,tr("历史画笔")}}},{"eraser",{{Tool::Eraser,tr("橡皮擦 (E)")}}},
        {"gradient",{{Tool::Gradient,tr("渐变 (G)")},{Tool::Fill,tr("油漆桶")}}},{"blur",{{Tool::Blur,tr("模糊")},{Tool::Sharpen,tr("锐化")}}},
        {"dodge",{{Tool::Dodge,tr("减淡 (O)")},{Tool::Burn,tr("加深")},{Tool::Sponge,tr("海绵")}}},{"pen",{{Tool::Path,tr("路径 / 钢笔 (P)")}}},
        {"text",{{Tool::Text,tr("栅格化文字 (T)")}}},{"shape",{{Tool::ShapeRectangle,tr("矩形形状 (U)")},{Tool::ShapeEllipse,tr("椭圆形状")}}},
        {"hand",{{Tool::Hand,tr("抓手 (H)")}}},{"zoom",{{Tool::Zoom,tr("缩放 (Z)")}}}};
    const QMap<Tool,QString> shortcuts{{Tool::Move,"V"},{Tool::Rectangle,"M"},{Tool::Lasso,"L"},{Tool::MagicWand,"W"},{Tool::Crop,"C"},{Tool::Eyedropper,"I"},{Tool::Heal,"J"},{Tool::Brush,"B"},{Tool::Clone,"S"},{Tool::Eraser,"E"},{Tool::Gradient,"G"},{Tool::Dodge,"O"},{Tool::Path,"P"},{Tool::Text,"T"},{Tool::ShapeRectangle,"U"},{Tool::Hand,"H"},{Tool::Zoom,"Z"}};
    const QMap<Tool,QString> variantIcons{{Tool::Ellipse,"ellipseSelect"},{Tool::Polygon,"polygon"},{Tool::MagneticLasso,"magnetic"},{Tool::QuickSelection,"quick"},{Tool::ObjectSelection,"object"},{Tool::Ruler,"ruler"},{Tool::Slice,"slice"},{Tool::ColorReplace,"replace"},{Tool::Fill,"fill"},{Tool::Sharpen,"sharpen"},{Tool::Burn,"burn"},{Tool::Sponge,"sponge"},{Tool::ShapeEllipse,"ellipseShape"}};
    for(const auto &entry:groups){auto *button=new EditorToolButton(toolBar_);button->setObjectName("imageEditorToolGroup_"+entry.first);button->setFixedSize(36,30);button->setToolButtonStyle(Qt::ToolButtonIconOnly);auto *menu=new QMenu(button);for(const auto &[id,name]:entry.second){auto *a=new QAction(toolIcon(variantIcons.value(id,entry.first)),name,this);a->setObjectName("imageEditorTool_"+QString::number(int(id)));a->setCheckable(true);group->addAction(a);addAction(a);if(shortcuts.contains(id))a->setShortcut(QKeySequence(shortcuts[id]));menu->addAction(a);connect(a,&QAction::triggered,this,[this,a,button,id]{button->setDefaultAction(a);setEditorTool(int(id));});if(id==entry.second.first().first)button->setDefaultAction(a);if(id==Tool::Hand)a->setChecked(true);}if(entry.second.size()>1){button->setMenu(menu);button->setPopupMode(QToolButton::MenuButtonPopup);button->setStyleSheet("QToolButton::menu-button { subcontrol-origin: padding; subcontrol-position: bottom right; width: 11px; height: 10px; border: 0; } QToolButton::menu-arrow { width: 7px; height: 6px; }");}button->setContextMenuPolicy(Qt::CustomContextMenu);connect(button,&QWidget::customContextMenuRequested,button,[menu,button](QPoint point){menu->exec(button->mapToGlobal(QPoint(button->width(),button->height())));});button->setToolTip(entry.second.first().second+(entry.second.size()>1?tr("\n右键切换同组工具"):QString()));toolBar_->addWidget(button);}
    auto *swatches=new QWidget(toolBar_);swatches->setFixedSize(40,52);auto *background=new QPushButton(swatches);background->setObjectName("imageEditorBackgroundColor");background->setGeometry(14,20,24,24);background->setStyleSheet("background:white;border:1px solid #aaa");background->setToolTip(tr("背景色 / 渐变终点"));color_=new QPushButton(swatches);color_->setGeometry(3,9,24,24);color_->setObjectName("imageEditorBrushColor");connect(background,&QPushButton::clicked,this,[this,background]{const auto c=QColorDialog::getColor(backgroundColor_,this,tr("背景色"));if(c.isValid()){backgroundColor_=c;tools_->setGradientEndColor(c);background->setStyleSheet(QString("background:%1;border:1px solid #aaa").arg(c.name()));}});connect(color_,&QPushButton::clicked,this,[this]{const auto c=QColorDialog::getColor(tools_->brushColor(),this,tr("前景色"),QColorDialog::ShowAlphaChannel);if(c.isValid()){tools_->setBrushColor(c);updateColorButton();}});toolBar_->addWidget(swatches);
    auto *options=addToolBar(tr("工具选项"));options->setObjectName("imageEditorBrushOptions");options->setMovable(false);options->setFloatable(false);options->setMinimumHeight(35);auto *toolAlign=new QWidget(options);toolAlign->setFixedWidth(toolBar_->width());options->addWidget(toolAlign);toolName_=new QLabel(options);toolName_->setObjectName("imageEditorToolName");toolName_->setMinimumWidth(90);options->addWidget(toolName_);options->addSeparator();
    moveOptions_=optionGroup(options);auto *moveLayout=qobject_cast<QHBoxLayout *>(moveOptions_->layout());layerX_=new QSpinBox(moveOptions_);layerY_=new QSpinBox(moveOptions_);layerWidth_=new QSpinBox(moveOptions_);layerHeight_=new QSpinBox(moveOptions_);for(auto *spin:{layerX_,layerY_,layerWidth_,layerHeight_}){spin->setRange(-1000000,1000000);spin->setFixedWidth(82);}layerWidth_->setMinimum(1);layerHeight_->setMinimum(1);layerX_->setObjectName("imageEditorLayerX");layerY_->setObjectName("imageEditorLayerY");layerWidth_->setObjectName("imageEditorLayerWidth");layerHeight_->setObjectName("imageEditorLayerHeight");for(const auto &[label,spin]:QList<QPair<QString,QSpinBox *>>{{"X",layerX_},{"Y",layerY_},{tr("宽"),layerWidth_},{tr("高"),layerHeight_}}){moveLayout->addWidget(new QLabel(label,moveOptions_));moveLayout->addWidget(spin);}auto *applyBounds=new QPushButton(tr("应用"),moveOptions_);applyBounds->setObjectName("imageEditorApplyLayerBounds");connect(applyBounds,&QPushButton::clicked,this,&ImageEditorWindow::transformLayerValues);moveLayout->addWidget(applyBounds);for(auto *a:{freeTransform,mergeDown}){auto *button=new QToolButton(moveOptions_);button->setDefaultAction(a);button->setToolButtonStyle(Qt::ToolButtonTextOnly);moveLayout->addWidget(button);}moveOptions_->setToolTip(tr("位置和尺寸采用画布像素。Ctrl+T 自由变换；Enter 提交；Esc 取消。"));
    brushOptions_=optionGroup(options);auto *brushLayout=qobject_cast<QHBoxLayout *>(brushOptions_->layout());brushLayout->addWidget(new QLabel(tr("大小")));auto *diameter=new QSpinBox(brushOptions_);diameter->setObjectName("imageEditorBrushDiameter");diameter->setRange(1,1024);diameter->setValue(24);diameter->setFixedWidth(70);brushLayout->addWidget(diameter);connect(diameter,&QSpinBox::valueChanged,this,[this](int value){tools_->setBrushRadius(value/2.);canvas_->update();});brushLayout->addWidget(new QLabel(tr("不透明度")));auto *opacity=new QSpinBox(brushOptions_);opacity->setObjectName("imageEditorBrushOpacity");opacity->setRange(1,100);opacity->setValue(100);opacity->setSuffix("%");opacity->setFixedWidth(75);brushLayout->addWidget(opacity);connect(opacity,&QSpinBox::valueChanged,this,[this](int v){tools_->setBrushOpacity(v/100.);});
    selectionOptions_=optionGroup(options);auto *selectionLayout=qobject_cast<QHBoxLayout *>(selectionOptions_->layout());auto *mode=new QComboBox(selectionOptions_);mode->setObjectName("imageEditorSelectionMode");mode->addItems({tr("新选区"),tr("添加"),tr("减去"),tr("相交")});selectionLayout->addWidget(mode);connect(mode,&QComboBox::currentIndexChanged,this,[this](int index){canvas_->setSelectionMode(ImageSelectionMode(index));});selectionLayout->addWidget(new QLabel(tr("容差")));auto *tolerance=new QSpinBox(selectionOptions_);tolerance->setObjectName("imageEditorTolerance");tolerance->setRange(0,100);tolerance->setValue(15);tolerance->setSuffix("%");tolerance->setFixedWidth(70);selectionLayout->addWidget(tolerance);connect(tolerance,&QSpinBox::valueChanged,this,[this](int v){tools_->setTolerance(v/100.);});
    textOptions_=optionGroup(options);auto *textLayout=qobject_cast<QHBoxLayout *>(textOptions_->layout());text_=new QLineEdit(tr("文字"),textOptions_);text_->setObjectName("imageEditorTextInput");text_->setMaximumWidth(210);font_=new QFontComboBox(textOptions_);font_->setMaximumWidth(160);fontSize_=new QSpinBox(textOptions_);fontSize_->setObjectName("imageEditorTextSize");fontSize_->setRange(1,512);fontSize_->setValue(32);fontSize_->setSuffix(" px");textLayout->addWidget(text_);textLayout->addWidget(font_);textLayout->addWidget(fontSize_);auto *bold=new QCheckBox(tr("加粗"),textOptions_),*italic=new QCheckBox(tr("斜体"),textOptions_);bold->setObjectName("imageEditorTextBold");italic->setObjectName("imageEditorTextItalic");auto *spacing=new QDoubleSpinBox(textOptions_);spacing->setObjectName("imageEditorTextSpacing");spacing->setRange(.2,10);spacing->setSingleStep(.1);spacing->setValue(1.2);spacing->setToolTip(tr("行距(倍)"));spacing->setMaximumWidth(70);textLayout->addWidget(bold);textLayout->addWidget(italic);textLayout->addWidget(spacing);auto updateText=[this,bold,italic,spacing]{auto f=font_->currentFont();f.setPixelSize(fontSize_->value());f.setBold(bold->isChecked());f.setItalic(italic->isChecked());tools_->setText(text_->text(),f,spacing->value());};connect(bold,&QCheckBox::toggled,this,updateText);connect(italic,&QCheckBox::toggled,this,updateText);connect(spacing,&QDoubleSpinBox::valueChanged,this,updateText);connect(text_,&QLineEdit::textChanged,this,updateText);connect(font_,&QFontComboBox::currentFontChanged,this,updateText);connect(fontSize_,&QSpinBox::valueChanged,this,updateText);updateText();
    cropOptions_=optionGroup(options);auto *cropLayout=qobject_cast<QHBoxLayout *>(cropOptions_->layout());auto *cropRatio=new QComboBox(cropOptions_);cropRatio->setObjectName("imageEditorCropRatio");cropRatio->addItems({tr("自由比例"),"1:1","16:9","4:3","3:4","9:16",tr("自定义比例")});cropLayout->addWidget(cropRatio);auto *cropWidth=new QDoubleSpinBox(cropOptions_),*cropHeight=new QDoubleSpinBox(cropOptions_);for(auto *spin:{cropWidth,cropHeight}){spin->setRange(.01,10000);spin->setDecimals(2);spin->setMaximumWidth(88);}cropWidth->setValue(16);cropHeight->setValue(9);cropWidth->setObjectName("imageEditorCropRatioWidth");cropHeight->setObjectName("imageEditorCropRatioHeight");cropLayout->addWidget(cropWidth);cropLayout->addWidget(cropHeight);auto cropAspect=[this,cropRatio,cropWidth,cropHeight]{const int index=cropRatio->currentIndex();const QList<double> ratios{0,1,16./9,4./3,3./4,9./16};cropWidth->setVisible(index==6);cropHeight->setVisible(index==6);canvas_->setCropAspect(index==6?cropWidth->value()/cropHeight->value():ratios[index]);};connect(cropRatio,&QComboBox::currentIndexChanged,this,cropAspect);connect(cropWidth,&QDoubleSpinBox::valueChanged,this,cropAspect);connect(cropHeight,&QDoubleSpinBox::valueChanged,this,cropAspect);cropAspect();
    selectionOptions_->setToolTip(tr("Shift 添加；Alt 减去；Shift+Alt 相交；Enter 完成；Esc 取消。"));brushOptions_->setToolTip(tr("图章 / 源修复：Alt 点击取样源。"));textOptions_->setToolTip(tr("点击画布新建独立文字像素图层。"));
    auto *colorDock=new QDockWidget(tr("颜色"),this);colorDock->setObjectName("imageEditorColorDock");auto *colorTabs=new QTabWidget(colorDock);auto *field=new EditorColorField(colorTabs,[this](QColor c){tools_->setBrushColor(c);updateColorButton();});field->setObjectName("imageEditorColorField");colorTabs->addTab(field,tr("颜色"));auto *swatchPage=new QWidget(colorTabs);auto *swatchGrid=new QGridLayout(swatchPage);const QList<QColor> colors{Qt::black,Qt::white,QColor("#808080"),Qt::red,Qt::green,Qt::blue,Qt::cyan,Qt::magenta,Qt::yellow,QColor("#804000"),QColor("#ff8000"),QColor("#8000ff")};for(int i=0;i<colors.size();++i){auto *b=new QPushButton(swatchPage);b->setMinimumSize(28,28);b->setStyleSheet(QString("background:%1;border:1px solid #777").arg(colors[i].name()));b->setToolTip(colors[i].name());swatchGrid->addWidget(b,i/4,i%4);connect(b,&QPushButton::clicked,this,[this,c=colors[i]]{tools_->setBrushColor(c);updateColorButton();});}colorTabs->addTab(swatchPage,tr("色板"));colorDock->setWidget(colorTabs);colorDock->setMinimumWidth(245);colorDock->setMaximumWidth(350);addDockWidget(Qt::RightDockWidgetArea,colorDock);windowMenu->addAction(colorDock->toggleViewAction());
    auto *propertiesDock=new QDockWidget(tr("属性"),this);propertiesDock->setObjectName("imageEditorPropertiesDock");auto *propertyTabs=new QTabWidget(propertiesDock);properties_=new QLabel(propertyTabs);properties_->setMargin(9);properties_->setAlignment(Qt::AlignTop|Qt::AlignLeft);properties_->setWordWrap(true);propertyTabs->addTab(properties_,tr("属性"));auto *adjustPage=new QWidget(propertyTabs);auto *adjustGrid=new QGridLayout(adjustPage);for(int i=0;i<7;++i){auto label=adjustmentNames[i];label.remove(QChar(0x2026));auto *button=new QPushButton(label,adjustPage);adjustGrid->addWidget(button,i/2,i%2);connect(button,&QPushButton::clicked,this,[this,i]{adjustImage(i);});}propertyTabs->addTab(adjustPage,tr("调整"));propertiesDock->setWidget(propertyTabs);addDockWidget(Qt::RightDockWidgetArea,propertiesDock);windowMenu->addAction(propertiesDock->toggleViewAction());
    auto *layerDock=new QDockWidget(tr("图层"),this);layerDock->setObjectName("imageEditorLayersDock");auto *layerTabs=new QTabWidget(layerDock);auto *layerPanel=new QWidget(layerTabs);auto *layerLayout=new QVBoxLayout(layerPanel);layerLayout->setContentsMargins(5,5,5,5);auto *row=new QHBoxLayout;blend_=new QComboBox(layerPanel);blend_->setObjectName("imageEditorLayerBlend");blend_->addItems({tr("正常"),tr("正片叠底"),tr("滤色"),tr("叠加"),tr("变暗"),tr("变亮"),tr("颜色减淡"),tr("颜色加深"),tr("线性减淡"),tr("线性加深"),tr("柔光"),tr("强光"),tr("差值"),tr("排除"),tr("减去"),tr("划分")});blend_->setSizePolicy(QSizePolicy::Expanding,QSizePolicy::Fixed);row->addWidget(blend_,1);layerOpacity_=new QDoubleSpinBox(layerPanel);layerOpacity_->setObjectName("imageEditorLayerOpacity");layerOpacity_->setRange(0,100);layerOpacity_->setSuffix("%");layerOpacity_->setDecimals(1);layerOpacity_->setFixedWidth(85);row->addWidget(layerOpacity_);layerLayout->addLayout(row);auto *mask=new QCheckBox(tr("编辑蒙版(黑隐藏 / 白显示)"),layerPanel);mask->setObjectName("imageEditorEditMask");connect(mask,&QCheckBox::toggled,this,[this](bool enabled){canvas_->cancelGesture();tools_->setEditingMask(enabled);});layerLayout->addWidget(mask);
    auto *groupMode=new QCheckBox(tr("图层组穿透"),layerPanel);groupMode->setObjectName("imageEditorGroupPassThrough");layerLayout->addWidget(groupMode);connect(groupMode,&QCheckBox::toggled,this,[this](bool enabled){auto l=activeLayer(document_,tools_->layer());if(l.group){l.passThrough=enabled;document_->updateLayer(l,tr("图层组穿透"));}});auto *clipping=new QCheckBox(tr("剪贴到下方图层"),layerPanel);clipping->setObjectName("imageEditorLayerClipping");layerLayout->addWidget(clipping);connect(clipping,&QCheckBox::toggled,this,[this](bool enabled){auto l=activeLayer(document_,tools_->layer());if(!l.id.isNull()&&!l.group){l.clipping=enabled;document_->updateLayer(l,tr("剪贴蒙版"));}});
    auto *maskPreview=new QCheckBox(tr("单独查看蒙版"),layerPanel);maskPreview->setObjectName("imageEditorMaskPreview");layerLayout->addWidget(maskPreview);connect(maskPreview,&QCheckBox::toggled,this,[this](bool enabled){canvas_->setMaskPreview(enabled);pages_[activePage_].maskPreview=enabled;});
    layers_=new QTreeWidget(layerPanel);layers_->setObjectName("imageEditorLayers");layers_->setColumnCount(1);layers_->setHeaderHidden(true);layers_->setIndentation(14);layers_->setUniformRowHeights(true);layers_->setAllColumnsShowFocus(true);layers_->setSelectionMode(QAbstractItemView::SingleSelection);layers_->viewport()->setPalette(editorPalette);layers_->viewport()->setAutoFillBackground(true);layerLayout->addWidget(layers_,1);auto *buttons=new QHBoxLayout;for(const auto &[name,fn]:QList<QPair<QString,std::function<void()>>>{{tr("+"),[this]{addLayer();}},{tr("复制"),[this]{duplicateLayer();}},{tr("↑"),[this]{reorderLayer(1);}},{tr("↓"),[this]{reorderLayer(-1);}},{tr("删除"),[this]{deleteLayer();}}}){auto *b=new QPushButton(name,layerPanel);b->setMaximumWidth(name.size()>1?56:32);connect(b,&QPushButton::clicked,this,fn);buttons->addWidget(b);}layerLayout->addLayout(buttons);auto *lockRow=new QHBoxLayout;lockRow->addStretch();auto *lockButton=new QToolButton(layerPanel);lockButton->setObjectName("imageEditorLockButton");lockButton->setToolButtonStyle(Qt::ToolButtonTextOnly);findChild<QAction *>("imageEditorLockLayer")->setCheckable(true);lockButton->setDefaultAction(findChild<QAction *>("imageEditorLockLayer"));lockRow->addWidget(lockButton);layerLayout->addLayout(lockRow);layerTabs->addTab(layerPanel,tr("图层"));
    layers_->setContextMenuPolicy(Qt::CustomContextMenu);connect(layers_,&QWidget::customContextMenuRequested,this,[this](QPoint at){if(auto *item=layers_->itemAt(at))layers_->setCurrentItem(item);QMenu menu(this);for(const auto &name:{"imageEditorAddLayer","imageEditorAddGroup","imageEditorDuplicateLayer","imageEditorGroupLayer","imageEditorExportLayer","imageEditorMergeDown","imageEditorMergeVisible","imageEditorFlatten","imageEditorLockLayer","imageEditorRenameLayer","imageEditorVisibility","imageEditorBlendingOptions","imageEditorDeleteLayer"})if(auto *a=findChild<QAction *>(name))menu.addAction(a);menu.exec(layers_->viewport()->mapToGlobal(at));});
    auto *channels=new QWidget(layerTabs);auto *channelLayout=new QVBoxLayout(channels);auto *channelGroup=new QActionGroup(this);const QStringList names{tr("RGB 合成"),tr("红"),tr("绿"),tr("蓝"),tr("Alpha")};for(int i=0;i<names.size();++i){auto *b=new QToolButton(channels);auto *a=new QAction(names[i],this);a->setObjectName("imageEditorChannel_"+QString::number(i-1));a->setCheckable(true);channelGroup->addAction(a);b->setDefaultAction(a);b->setToolButtonStyle(Qt::ToolButtonTextOnly);channelLayout->addWidget(b);if(i==0)a->setChecked(true);connect(a,&QAction::triggered,this,[this,i]{canvas_->setPreviewChannel(i-1);});}channelLayout->addStretch();layerTabs->addTab(channels,tr("通道"));auto *history=new QUndoView(document_->history(),layerTabs);history->setObjectName("imageEditorHistory");history->setEmptyLabel(tr("打开图片"));layerTabs->addTab(history,tr("历史"));auto *paths=new QWidget(layerTabs);auto *pathLayout=new QVBoxLayout(paths);pathLayout->addWidget(new QLabel(tr("钢笔逐点建路径，Enter 描边。"),paths));for(const auto &[name,fn]:QList<QPair<QString,std::function<void()>>>{{tr("填充路径"),[this]{canvas_->fillVectorPath();}},{tr("描边路径"),[this]{canvas_->strokeVectorPath();}},{tr("路径转选区"),[this]{canvas_->selectVectorPath();}}}){auto *b=new QPushButton(name,paths);connect(b,&QPushButton::clicked,this,fn);pathLayout->addWidget(b);}pathLayout->addStretch();layerTabs->addTab(paths,tr("路径"));layerDock->setWidget(layerTabs);addDockWidget(Qt::RightDockWidgetArea,layerDock);windowMenu->addAction(layerDock->toggleViewAction());windowMenu->addAction(toolBar_->toggleViewAction());windowMenu->addAction(options->toggleViewAction());resizeDocks({colorDock,propertiesDock,layerDock},{220,180,420},Qt::Vertical);resizeDocks({layerDock},{265},Qt::Horizontal);
    connect(layers_,&QTreeWidget::currentItemChanged,this,[this](QTreeWidgetItem *item){if(!item)return;const auto id=item->data(0,Qt::UserRole).toUuid();if(tools_->layer()!=id){canvas_->cancelGesture();tools_->setLayer(id);}updateProperties();canvas_->setMaskPreview(findChild<QCheckBox *>("imageEditorMaskPreview")->isChecked());canvas_->update();});connect(layers_,&QTreeWidget::itemClicked,this,[this](QTreeWidgetItem *item,int){if(!item)return;tools_->setLayer(item->data(0,Qt::UserRole).toUuid());setEditorTool(int(ImageEditorTool::Move));updateProperties();canvas_->update();});connect(layers_,&QTreeWidget::itemDoubleClicked,this,[this](QTreeWidgetItem *,int){renameLayer();});connect(layers_,&QTreeWidget::itemChanged,this,[this](QTreeWidgetItem *item){auto l=activeLayer(document_,item->data(0,Qt::UserRole).toUuid());if(l.id.isNull())return;l.visible=item->checkState(0)==Qt::Checked;document_->updateLayer(l,tr("图层可见性"));});connect(layerOpacity_,&QDoubleSpinBox::valueChanged,this,[this](double value){auto l=activeLayer(document_,tools_->layer());if(!l.id.isNull()){l.opacity=float(value/100);document_->updateLayer(l,tr("图层不透明度"));}});connect(blend_,&QComboBox::currentIndexChanged,this,[this](int value){auto l=activeLayer(document_,tools_->layer());if(!l.id.isNull()){l.blend=ImageBlendMode(value);document_->updateLayer(l,tr("图层混合"));}});
    cursorPosition_=new QLabel(this);cursorPosition_->setObjectName("imageEditorCursorPosition");cursorPosition_->setMinimumWidth(190);statusBar()->addPermanentWidget(cursorPosition_);
    connectDocument(document_,tools_,canvas_);setEditorTool(int(Tool::Hand));updateColorButton();rebuildLayers();updateStatus();canvas_->fitToWindow();QTimer::singleShot(0,canvas_,[this,canvas=canvas_]{canvas->setNativeHdrEnabled(true);if(canvas==canvas_)updateStatus();});

}
QWidget *ImageEditorWindow::makePage(ImageEditorCanvas *canvas){
    auto *host=new QWidget(this);auto *grid=new QGridLayout(host);grid->setContentsMargins(0,0,0,0);grid->setSpacing(0);auto *horizontal=new EditorRuler(canvas,false,host);horizontal->setObjectName("imageEditorHorizontalRuler");auto *vertical=new EditorRuler(canvas,true,host);vertical->setObjectName("imageEditorVerticalRuler");grid->addWidget(horizontal,0,1);grid->addWidget(vertical,1,0);grid->addWidget(canvas,1,1);grid->setColumnStretch(1,1);grid->setRowStretch(1,1);if(auto *a=findChild<QAction *>("imageEditorRulers")){horizontal->setVisible(a->isChecked());vertical->setVisible(a->isChecked());}return host;
}
void ImageEditorWindow::connectDocument(ImageDocument *doc,ImageEditorTools *tools,ImageEditorCanvas *canvas){
    connect(tools,&ImageEditorTools::layerChanged,this,[this,doc](const QUuid &){if(doc!=document_)return;rebuildLayers();canvas_->update();});
    connect(canvas,&ImageEditorCanvas::toolChanged,this,[this,canvas](ImageEditorTool tool){if(canvas==canvas_)setEditorTool(int(tool));});
    connect(canvas,&ImageEditorCanvas::cursorPositionChanged,this,[this,canvas](QPointF point,bool visible){if(canvas!=canvas_)return;cursorPosition_->setText(visible?tr("X %1 px   Y %2 px").arg(point.x(),0,'f',1).arg(point.y(),0,'f',1):QString());if(canvas->freeTransformActive())updateProperties();});
    connect(tools,&ImageEditorTools::errorOccurred,this,[this,doc](const QString &e){if(doc==document_)QMessageBox::warning(this,tr("图像编辑"),e);});
    connect(canvas,&ImageEditorCanvas::colorPicked,this,[this,canvas]{if(canvas==canvas_)updateColorButton();});
    connect(canvas,&ImageEditorCanvas::textEditRequested,this,[this,canvas](const QUuid &id){if(canvas==canvas_)editTextLayer(id);});
    connect(canvas,&ImageEditorCanvas::rulerMeasured,this,[this,canvas](double distance,double angle){if(canvas==canvas_)statusBar()->showMessage(tr("测量：%1 px · %2°").arg(distance,0,'f',2).arg(angle,0,'f',2));});
    connect(canvas,&ImageEditorCanvas::sliceCreated,this,[this,doc](QRect region){if(doc!=document_)return;const auto path=QFileDialog::getSaveFileName(this,tr("导出切片 PNG"),QFileInfo(sourcePath_).absolutePath()+"/slice.png",tr("PNG (*.png)"));if(path.isEmpty())return;if(isSourcePath(path)){QMessageBox::warning(this,tr("切片导出"),tr("请选择新路径以保留源文件。"));return;}const auto error=ImageEditorTools::savePngRegion(doc,region,path);if(!error.isEmpty())QMessageBox::warning(this,tr("切片导出"),error);});
    connect(canvas,&ImageEditorCanvas::selectionContextMenuRequested,this,[this,canvas](QPoint position){if(canvas!=canvas_)return;QMenu menu(this);for(const auto *name:{"imageEditorLayerCut","imageEditorLayerCopy","imageEditorDeselect","imageEditorInvertSelection"})menu.addAction(findChild<QAction *>(name));menu.exec(position);});
    connect(canvas,&ImageEditorCanvas::viewChanged,this,[this,canvas]{if(canvas==canvas_)updateStatus();});
    connect(canvas,&ImageEditorCanvas::previewReady,this,[this,canvas]{if(canvas!=canvas_)return;findChild<QAction *>("imageEditorNativeHdr")->setChecked(canvas->nativeHdrActive());updateStatus();});
    connect(canvas,&ImageEditorCanvas::previewError,this,[this,canvas](const QString &error){if(canvas==canvas_&&lastPreviewError_!=error){lastPreviewError_=error;statusBar()->showMessage(error,10000);}});
    connect(doc,&ImageDocument::changed,this,[this,doc]{if(doc==document_){rebuildLayers();updateStatus();}});
    connect(doc->history(),&QUndoStack::canUndoChanged,this,[this,doc](bool enabled){if(doc==document_)findChild<QAction *>("imageEditorUndo")->setEnabled(enabled);});
    connect(doc->history(),&QUndoStack::canRedoChanged,this,[this,doc](bool enabled){if(doc==document_)findChild<QAction *>("imageEditorRedo")->setEnabled(enabled);});
    connect(doc->history(),&QUndoStack::cleanChanged,this,[this,doc](bool clean){for(int i=0;i<pages_.size();++i)if(pages_[i].document==doc){auto label=documentTab_->tabText(i);if(label.endsWith(" *"))label.chop(2);if(!clean)label+=" *";documentTab_->setTabText(i,label);break;}if(doc==document_)setWindowModified(!clean);});
}
void ImageEditorWindow::addImage(const QImage &image,const QString &path){
    auto *doc=new ImageDocument(image.size(),precisionFor(image));doc->setColorSpace(image.colorSpace());doc->setMetadata("sourcePath",path);const auto id=doc->addLayer(tr("背景"),image);auto layer=activeLayer(doc,id);layer.locked=true;doc->updateLayer(layer);doc->history()->clear();doc->history()->setClean();addDocument(doc,path);
}
void ImageEditorWindow::addDocument(ImageDocument *doc,const QString &path){
    if(!doc)return;const QFileInfo file(path);if(file.exists())for(int i=0;i<pages_.size();++i)if(QFileInfo(pages_[i].path).absoluteFilePath().compare(file.absoluteFilePath(),Qt::CaseInsensitive)==0){if(doc!=pages_[i].document)delete doc;activateDocument(i);return;}
    doc->setParent(this);auto *tools=new ImageEditorTools(doc,this);const auto source=doc->layers();for(auto i=source.crbegin();i!=source.crend();++i)if(!i->group){tools->setLayer(i->id);break;}auto *canvas=new ImageEditorCanvas(tools,this);const auto transfer=doc->colorSpace().transferFunction();if(transfer==QColorSpace::TransferFunction::St2084||transfer==QColorSpace::TransferFunction::Hlg){auto settings=canvas->hdrPreviewSettings();settings.toneMap=true;settings.whitePoint=transfer==QColorSpace::TransferFunction::St2084?64:12;canvas->setHdrPreviewSettings(settings);}pages_.append({doc,tools,canvas,path});pagesStack_->addWidget(makePage(canvas));canvas->setShowGrid(findChild<QAction *>("imageEditorGrid")->isChecked());connectDocument(doc,tools,canvas);{const QSignalBlocker guard(documentTab_);documentTab_->addTab(QFileInfo(path).fileName());}activateDocument(pages_.size()-1);canvas->fitToWindow();QTimer::singleShot(0,canvas,[this,canvas]{canvas->setNativeHdrEnabled(true);if(canvas==canvas_)updateStatus();});
}
void ImageEditorWindow::savePageSettings(){if(activePage_<0||activePage_>=pages_.size())return;auto &page=pages_[activePage_];page.text=text_->text();page.font=font_->currentFont();page.font.setBold(findChild<QCheckBox *>("imageEditorTextBold")->isChecked());page.font.setItalic(findChild<QCheckBox *>("imageEditorTextItalic")->isChecked());page.textLineSpacing=findChild<QDoubleSpinBox *>("imageEditorTextSpacing")->value();page.fontSize=fontSize_->value();page.selectionMode=findChild<QComboBox *>("imageEditorSelectionMode")->currentIndex();page.cropRatio=findChild<QComboBox *>("imageEditorCropRatio")->currentIndex();page.cropWidth=findChild<QDoubleSpinBox *>("imageEditorCropRatioWidth")->value();page.cropHeight=findChild<QDoubleSpinBox *>("imageEditorCropRatioHeight")->value();}
void ImageEditorWindow::activateDocument(int index){
    if(index<0||index>=pages_.size())return;savePageSettings();if(activePage_>=0&&index!=activePage_)pages_[activePage_].canvas->cancelGesture();
    activePage_=index;const auto &page=pages_[index];document_=page.document;tools_=page.tools;canvas_=page.canvas;sourcePath_=page.path;pagesStack_->setCurrentIndex(index);{const QSignalBlocker guard(documentTab_);documentTab_->setCurrentIndex(index);}layerItems_.clear();layerStructure_.clear();{const QSignalBlocker guard(layers_);layers_->clear();}
    findChild<QUndoView *>("imageEditorHistory")->setStack(document_->history());findChild<QAction *>("imageEditorUndo")->setEnabled(document_->history()->canUndo());findChild<QAction *>("imageEditorRedo")->setEnabled(document_->history()->canRedo());setWindowModified(!document_->history()->isClean());setWindowTitle(tr("图像编辑 · %1[*]").arg(QFileInfo(sourcePath_).fileName()));cursorPosition_->clear();lastPreviewError_.clear();
    auto *diameter=findChild<QSpinBox *>("imageEditorBrushDiameter"),*opacity=findChild<QSpinBox *>("imageEditorBrushOpacity"),*tolerance=findChild<QSpinBox *>("imageEditorTolerance");const QSignalBlocker d(diameter),o(opacity),t(tolerance);diameter->setValue(qRound(tools_->brushRadius()*2));opacity->setValue(qRound(tools_->brushOpacity()*100));tolerance->setValue(qRound(tools_->tolerance()*100));auto *mask=findChild<QCheckBox *>("imageEditorMaskPreview");{const QSignalBlocker guard(mask);mask->setChecked(page.maskPreview);}findChild<QComboBox *>("imageEditorSelectionMode")->setCurrentIndex(page.selectionMode);findChild<QDoubleSpinBox *>("imageEditorCropRatioWidth")->setValue(page.cropWidth);findChild<QDoubleSpinBox *>("imageEditorCropRatioHeight")->setValue(page.cropHeight);findChild<QComboBox *>("imageEditorCropRatio")->setCurrentIndex(page.cropRatio);text_->setText(page.text.isEmpty()?tr("文字"):page.text);font_->setCurrentFont(page.font);fontSize_->setValue(page.fontSize);findChild<QCheckBox *>("imageEditorTextBold")->setChecked(page.font.bold());findChild<QCheckBox *>("imageEditorTextItalic")->setChecked(page.font.italic());findChild<QDoubleSpinBox *>("imageEditorTextSpacing")->setValue(page.textLineSpacing);auto textFont=page.font;textFont.setPixelSize(fontSize_->value());tools_->setText(text_->text(),textFont,page.textLineSpacing);
    const auto settings=canvas_->hdrPreviewSettings();findChild<QAction *>("imageEditorChannel_"+QString::number(settings.channel))->setChecked(true);{const QSignalBlocker guard(findChild<QAction *>("imageEditorHdrToneMap"));findChild<QAction *>("imageEditorHdrToneMap")->setChecked(settings.toneMap);}findChild<QAction *>("imageEditorNativeHdr")->setChecked(canvas_->nativeHdrActive());setEditorTool(int(canvas_->tool()));updateColorButton();rebuildLayers();updateStatus();
}
void ImageEditorWindow::closeDocument(int index){
    if(index<0||index>=pages_.size())return;if(pages_.size()==1){close();return;}const auto page=pages_[index];page.canvas->cancelGesture();if(!page.document->history()->isClean()&&QMessageBox::question(this,tr("关闭文档"),tr("%1 有未保存的图层与编辑，确定关闭？").arg(QFileInfo(page.path).fileName()),QMessageBox::Yes|QMessageBox::No,QMessageBox::No)!=QMessageBox::Yes)return;
    savePageSettings();const int next=index==activePage_?std::max(0,index-1):activePage_-(index<activePage_?1:0);auto *host=pagesStack_->widget(index);{const QSignalBlocker guard(documentTab_);documentTab_->removeTab(index);}pagesStack_->removeWidget(host);pages_.removeAt(index);activePage_=-1;document_=nullptr;tools_=nullptr;canvas_=nullptr;delete host;delete page.tools;delete page.document;activateDocument(next);
}
void ImageEditorWindow::setEditorTool(int value){
    if(canvas_->tool()!=ImageEditorTool(value))canvas_->setTool(ImageEditorTool(value));for(auto *a:findChildren<QAction *>())if(a->objectName()=="imageEditorTool_"+QString::number(value)){a->setChecked(true);toolName_->setText(a->text().section(" (",0,0));}
    const auto t=ImageEditorTool(value);const bool selection=t==ImageEditorTool::Rectangle || t==ImageEditorTool::Ellipse || t==ImageEditorTool::Lasso || t==ImageEditorTool::Polygon || t==ImageEditorTool::MagneticLasso || t==ImageEditorTool::MagicWand || t==ImageEditorTool::QuickSelection || t==ImageEditorTool::ObjectSelection;
    const bool brush=!selection && t!=ImageEditorTool::Move && t!=ImageEditorTool::Hand && t!=ImageEditorTool::Zoom && t!=ImageEditorTool::Text && t!=ImageEditorTool::Crop && t!=ImageEditorTool::Slice && t!=ImageEditorTool::Ruler;
    auto *bar=findChild<QToolBar *>("imageEditorBrushOptions");for(auto *a:bar->actions()){auto *widget=bar->widgetForAction(a);if(widget==textOptions_)a->setVisible(t==ImageEditorTool::Text);else if(widget==selectionOptions_)a->setVisible(selection);else if(widget==brushOptions_)a->setVisible(brush);else if(widget==cropOptions_)a->setVisible(t==ImageEditorTool::Crop);else if(widget==moveOptions_)a->setVisible(t==ImageEditorTool::Move);}
}
void ImageEditorWindow::rebuildLayers(){
    const QSignalBlocker a(layers_);const auto source=document_->layers();QList<QPair<QUuid,QUuid>> structure;for(auto i=source.crbegin();i!=source.crend();++i)structure.append({i->id,i->parentId});
    if(structure!=layerStructure_){QSet<QUuid> collapsed;for(auto i=layerItems_.cbegin();i!=layerItems_.cend();++i)if(!i.value()->isExpanded())collapsed.insert(i.key());layers_->clear();layerItems_.clear();for(auto i=source.crbegin();i!=source.crend();++i){auto *item=new QTreeWidgetItem;item->setData(0,Qt::UserRole,i->id);item->setFlags(item->flags()|Qt::ItemIsUserCheckable);layerItems_.insert(i->id,item);}for(auto i=source.crbegin();i!=source.crend();++i){auto *item=layerItems_.value(i->id),*parent=layerItems_.value(i->parentId);if(parent)parent->addChild(item);else layers_->addTopLevelItem(item);item->setExpanded(!collapsed.contains(i->id));}layerStructure_=structure;}
    for(const auto &layer:source){auto *item=layerItems_.value(layer.id);item->setText(0,layer.name+(layer.locked?tr("  [锁定]"):QString()));item->setCheckState(0,layer.visible?Qt::Checked:Qt::Unchecked);item->setToolTip(0,tr("%1 · %2 · %3%\n%4").arg(layer.name,layer.group?tr("图层组"):tr("像素图层")).arg(layer.opacity*100,0,'f',1).arg(layer.locked?tr("解锁后可编辑"):tr("点击选择并显示变换框；双击重命名")));}
    if(!layerItems_.contains(tools_->layer())){QUuid fallback;for(auto i=source.crbegin();i!=source.crend();++i)if(!i->group){fallback=i->id;break;}if(fallback.isNull()&&!source.isEmpty())fallback=source.last().id;tools_->setLayer(fallback);}layers_->setCurrentItem(layerItems_.value(tools_->layer()));updateProperties();
}
void ImageEditorWindow::updateProperties(){
    const auto layer=activeLayer(document_,tools_->layer());const auto documentBounds=canvas_->selectedLayerBounds().toAlignedRect();
    properties_->setText(tr("画布  %1 × %2 px\n\n%3\n%4\n位置  X %5  Y %6\n尺寸  %7 × %8 px\n蒙版  %9").arg(document_->size().width()).arg(document_->size().height()).arg(layer.name,layer.group?tr("图层组"):layer.locked?tr("锁定像素图层"):tr("像素图层")).arg(documentBounds.x()).arg(documentBounds.y()).arg(documentBounds.width()).arg(documentBounds.height()).arg(layer.maskEnabled?tr("启用"):tr("停用")));
    if(auto *lock=findChild<QAction *>("imageEditorLockLayer")){const QSignalBlocker guard(lock);lock->setChecked(layer.locked);lock->setEnabled(!layer.id.isNull());lock->setText(layer.locked?tr("解锁"):tr("上锁"));}const bool editable=!layer.id.isNull()&&!layer.locked;const QSignalBlocker opacityGuard(layerOpacity_),blendGuard(blend_),xGuard(layerX_),yGuard(layerY_),widthGuard(layerWidth_),heightGuard(layerHeight_);layerOpacity_->setEnabled(!layer.id.isNull());blend_->setEnabled(!layer.id.isNull());layerOpacity_->setValue(layer.opacity*100);blend_->setCurrentIndex(int(layer.blend));
    layerX_->setValue(documentBounds.x());layerY_->setValue(documentBounds.y());layerWidth_->setValue(std::max(1,documentBounds.width()));layerHeight_->setValue(std::max(1,documentBounds.height()));for(auto *spin:{layerX_,layerY_,layerWidth_,layerHeight_})spin->setEnabled(editable&&!tools_->editingMask()&&!canvas_->freeTransformActive());findChild<QPushButton *>("imageEditorApplyLayerBounds")->setEnabled(editable&&!tools_->editingMask()&&!canvas_->freeTransformActive());
    auto *group=findChild<QCheckBox *>("imageEditorGroupPassThrough"),*clip=findChild<QCheckBox *>("imageEditorLayerClipping"),*mask=findChild<QCheckBox *>("imageEditorEditMask");const QSignalBlocker groupGuard(group),clipGuard(clip),maskGuard(mask);group->setVisible(layer.group);group->setChecked(layer.passThrough);clip->setVisible(!layer.group);clip->setChecked(layer.clipping);mask->setEnabled(editable);mask->setChecked(tools_->editingMask());
    if(auto *transform=findChild<QAction *>("imageEditorFreeTransform"))transform->setEnabled(editable&&!documentBounds.isEmpty()&&!tools_->editingMask());if(auto *merge=findChild<QAction *>("imageEditorMergeDown")){bool canMerge=false;const auto source=document_->layers();for(int i=1;i<source.size();++i)if(source[i].id==layer.id){const auto &lower=source[i-1];canMerge=editable&&!layer.group&&layer.visible&&!lower.group&&!lower.locked&&lower.visible&&lower.parentId==layer.parentId&&!tools_->editingMask();break;}merge->setEnabled(canMerge);}
}
void ImageEditorWindow::updateStatus(){setWindowModified(!document_->history()->isClean());const auto size=document_->size();const auto precision=document_->precision()==ImagePrecision::Float32?QStringLiteral("RGB/32F"):document_->precision()==ImagePrecision::UInt16?QStringLiteral("RGB/16"):QStringLiteral("RGB/8");documentTab_->setTabText(activePage_,tr("%1 @ %2% (%3)%4").arg(QFileInfo(sourcePath_).fileName()).arg(canvas_->zoom()*100,0,'f',1).arg(precision).arg(document_->history()->isClean()?QString():" *"));statusBar()->showMessage(tr("%1 × %2 px · %3 · %4% · %5 · 缓存 %6 MiB%7").arg(size.width()).arg(size.height()).arg(precision).arg(canvas_->zoom()*100,0,'f',1).arg(canvas_->nativeHdrActive()?tr("scRGB / HDR 显示"):tr("SDR 显示预览")).arg(document_->residentBytes()/1048576.,0,'f',1).arg(document_->colorSpace().isValid()?QString():tr(" · 无源 ICC")));}
void ImageEditorWindow::updateColorButton(){backgroundColor_=tools_->gradientEndColor();if(auto *background=findChild<QPushButton *>("imageEditorBackgroundColor"))background->setStyleSheet(QString("background:%1;border:1px solid #aaa").arg(backgroundColor_.name()));const auto c=tools_->brushColor();color_->setStyleSheet(QString("background:%1;border:1px solid #bbb").arg(c.name()));color_->setToolTip(tr("前景色 %1").arg(c.name()));if(auto *field=findChild<QWidget *>("imageEditorColorField"))static_cast<EditorColorField *>(field)->setColor(c);}
void ImageEditorWindow::addLayer(){canvas_->cancelGesture();const auto l=activeLayer(document_,tools_->layer());document_->beginEdit(tr("新建图层"));const auto id=document_->addLayer(tr("图层 %1").arg(document_->layers().size()+1));auto info=activeLayer(document_,id);info.parentId=l.group?l.id:l.parentId;document_->updateLayer(info);document_->commitEdit();tools_->setLayer(id);rebuildLayers();}
void ImageEditorWindow::deleteLayer(){const auto layers=document_->layers();auto id=tools_->layer();for(int depth=0;!id.isNull()&&depth<=layers.size();++depth){QUuid parent;for(const auto &layer:layers)if(layer.id==id){if(layer.locked)return;parent=layer.parentId;break;}id=parent;}canvas_->cancelGesture();document_->removeLayer(tools_->layer());rebuildLayers();}
void ImageEditorWindow::duplicateLayer(){canvas_->cancelGesture();document_->beginEdit(tr("复制图层"));const auto id=document_->duplicateLayer(tools_->layer());if(id.isNull()){document_->cancelEdit();return;}auto layer=activeLayer(document_,id);layer.locked=false;document_->updateLayer(layer);document_->commitEdit();tools_->setLayer(id);rebuildLayers();}
void ImageEditorWindow::mergeLayerDown(){canvas_->cancelGesture();QString error;const auto id=document_->mergeDown(tools_->layer(),&error);if(id.isNull()){QMessageBox::warning(this,tr("向下合并"),error);return;}tools_->setLayer(id);rebuildLayers();canvas_->update();}
void ImageEditorWindow::addGroup(bool fromLayer){canvas_->cancelGesture();const auto current=activeLayer(document_,tools_->layer());QString error;const auto id=fromLayer?document_->groupLayer(current.id,tr("图层组"),&error):document_->createGroup(tr("图层组"),current.group?current.id:current.parentId);if(id.isNull()){if(!error.isEmpty())QMessageBox::warning(this,tr("图层组"),error);return;}tools_->setLayer(id);rebuildLayers();}
void ImageEditorWindow::mergeAll(bool flatten){canvas_->cancelGesture();QString error;const auto id=flatten?document_->flatten(&error):document_->mergeVisible(&error);if(id.isNull()){QMessageBox::warning(this,tr("合并图层"),error);return;}tools_->setLayer(id);rebuildLayers();}
void ImageEditorWindow::exportLayer(){
    canvas_->cancelGesture();const auto layer=activeLayer(document_,tools_->layer());if(layer.id.isNull())return;if(document_->precision()==ImagePrecision::Float32){QMessageBox::warning(this,tr("图层 PNG 导出"),tr("PNG 不能保留浮点数据，请导出浮点 TIFF。"));return;}const auto size=document_->size();if(qint64(size.width())*size.height()*(document_->precision()==ImagePrecision::UInt16?8:4)>256*1024*1024){QMessageBox::warning(this,tr("图层 PNG 导出"),tr("完整画布 PNG 导出暂限 256 MiB 像素数据。"));return;}const auto path=QFileDialog::getSaveFileName(this,tr("导出当前图层 PNG(保留画布大小)"),QFileInfo(sourcePath_).absolutePath()+"/"+layer.name+".png",tr("PNG (*.png)"));if(path.isEmpty())return;if(isSourcePath(path)){QMessageBox::warning(this,tr("导出图层"),tr("请选择新路径以保留源文件。"));return;}
    auto isolated=document_->snapshot();QSet<QUuid> keep;keep.insert(layer.id);auto parent=layer.parentId;while(!parent.isNull()){keep.insert(parent);parent=activeLayer(isolated.get(),parent).parentId;}if(layer.group)for(const auto &entry:isolated->layers()){auto ancestor=entry.parentId;while(!ancestor.isNull()){if(ancestor==layer.id){keep.insert(entry.id);break;}ancestor=activeLayer(isolated.get(),ancestor).parentId;}}
    for(auto info:isolated->layers()){info.visible=keep.contains(info.id);if(info.id==layer.id){info.blend=ImageBlendMode::Normal;info.clipping=false;}isolated->updateLayer(info);}const auto error=ImageEditorTools::savePng(isolated.get(),path);if(!error.isEmpty())QMessageBox::warning(this,tr("图层 PNG 导出"),error);else statusBar()->showMessage(tr("已导出当前图层；保留画布、蒙版和原位深。"),5000);
}
void ImageEditorWindow::blendingOptions(){
    canvas_->cancelGesture();const auto original=activeLayer(document_,tools_->layer());if(original.id.isNull())return;auto working=original;auto *doc=document_;auto *canvas=canvas_;QDialog dialog(this);dialog.setObjectName("imageEditorBlendingDialog");dialog.setAttribute(Qt::WA_WindowPropagation,true);dialog.setPalette(palette());dialog.setWindowTitle(tr("混合选项 · %1").arg(original.name));dialog.resize(540,530);QVBoxLayout layout(&dialog);auto *form=new QFormLayout;layout.addLayout(form);auto *blend=new QComboBox(&dialog);blend->setObjectName("imageEditorBlendingMode");for(int i=0;i<blend_->count();++i)blend->addItem(blend_->itemText(i));blend->setCurrentIndex(int(working.blend));form->addRow(tr("混合模式"),blend);auto *opacity=new QDoubleSpinBox(&dialog),*fill=new QDoubleSpinBox(&dialog);for(auto *spin:{opacity,fill}){spin->setRange(0,100);spin->setDecimals(1);spin->setSuffix("%");}opacity->setObjectName("imageEditorBlendingOpacity");fill->setObjectName("imageEditorBlendingFill");opacity->setValue(working.opacity*100);fill->setValue(working.fillOpacity*100);fill->setEnabled(!original.group);form->addRow(tr("不透明度"),opacity);form->addRow(tr("填充不透明度"),fill);auto *channels=new QWidget(&dialog);auto *channelRow=new QHBoxLayout(channels);channelRow->setContentsMargins(0,0,0,0);QList<QCheckBox *> enabledChannels;for(int i=0;i<3;++i){auto *box=new QCheckBox(QStringList{"R","G","B"}[i],channels);box->setObjectName("imageEditorBlendingChannel_"+QString::number(i));box->setChecked(working.channels&(1<<i));channelRow->addWidget(box);enabledChannels.append(box);}channelRow->addStretch();form->addRow(tr("高级混合通道"),channels);auto *channel=new QComboBox(&dialog);channel->setObjectName("imageEditorBlendIfChannel");channel->addItems({tr("灰色"),tr("红"),tr("绿"),tr("蓝")});channel->setCurrentIndex(int(working.blendIfChannel));form->addRow(tr("混合颜色带(Blend If)"),channel);
    auto *preview=new QCheckBox(tr("预览"),&dialog);preview->setObjectName("imageEditorBlendingPreview");preview->setChecked(true);std::function<void()> applyPreview=[&]{doc->updateLayer(preview->isChecked()?working:original);canvas->invalidateDocumentPreview();};
    QList<BlendRangeSlider *> sliders;QList<QList<QSpinBox *>> values;
    auto refreshRanges=[&]{for(int row=0;row<2;++row){const auto range=row?working.blendIfBackdrop[channel->currentIndex()]:working.blendIfSource[channel->currentIndex()];sliders[row]->setRange(range);for(int i=0;i<4;++i){const QSignalBlocker guard(values[row][i]);values[row][i]->setValue(qRound(range[i]*255));}}};
    for(int row=0;row<2;++row){layout.addWidget(new QLabel(row?tr("下一图层") : tr("本图层"),&dialog));auto changed=[&,row](ImageBlendRange range){auto &target=row?working.blendIfBackdrop[channel->currentIndex()]:working.blendIfSource[channel->currentIndex()];target=range;refreshRanges();applyPreview();};auto *slider=new BlendRangeSlider(&dialog,changed);slider->setObjectName(row?"imageEditorBlendBackdropRange":"imageEditorBlendSourceRange");sliders.append(slider);layout.addWidget(slider);auto *numbers=new QHBoxLayout;QList<QSpinBox *> spins;for(int i=0;i<4;++i){auto *spin=new QSpinBox(&dialog);spin->setRange(0,255);spin->setObjectName(QString(row?"imageEditorBlendBackdrop_%1":"imageEditorBlendSource_%1").arg(i));spin->setToolTip(QStringList{tr("黑色起点"),tr("黑色完全显示"),tr("白色完全显示"),tr("白色终点")}[i]);numbers->addWidget(spin);spins.append(spin);connect(spin,&QSpinBox::valueChanged,&dialog,[&,row,i](int v){auto range=row?working.blendIfBackdrop[channel->currentIndex()]:working.blendIfSource[channel->currentIndex()];range[i]=std::clamp(v/255.f,i?range[i-1]:0.f,i<3?range[i+1]:1.f);(row?working.blendIfBackdrop:working.blendIfSource)[channel->currentIndex()]=range;refreshRanges();applyPreview();});}values.append(spins);layout.addLayout(numbers);}
    layout.addWidget(new QLabel(tr("Alt 拆分黑白端点形成过渡；灰色与各 RGB 通道的已设范围同时生效。"),&dialog));layout.addWidget(preview);QDialogButtonBox buttons(QDialogButtonBox::Ok|QDialogButtonBox::Cancel|QDialogButtonBox::Reset);buttons.setObjectName("imageEditorBlendingButtons");layout.addWidget(&buttons);connect(&buttons,&QDialogButtonBox::accepted,&dialog,&QDialog::accept);connect(&buttons,&QDialogButtonBox::rejected,&dialog,&QDialog::reject);
    connect(blend,&QComboBox::currentIndexChanged,&dialog,[&](int value){working.blend=ImageBlendMode(value);if(working.group&&value!=0)working.passThrough=false;applyPreview();});connect(opacity,&QDoubleSpinBox::valueChanged,&dialog,[&](double value){working.opacity=float(value/100);applyPreview();});connect(fill,&QDoubleSpinBox::valueChanged,&dialog,[&](double value){working.fillOpacity=float(value/100);applyPreview();});for(auto *box:enabledChannels)connect(box,&QCheckBox::toggled,&dialog,[&]{working.channels=0;for(int i=0;i<enabledChannels.size();++i)if(enabledChannels[i]->isChecked())working.channels|=1<<i;applyPreview();});connect(channel,&QComboBox::currentIndexChanged,&dialog,[&](int value){working.blendIfChannel=ImageBlendIfChannel(value);refreshRanges();});connect(preview,&QCheckBox::toggled,&dialog,[&]{applyPreview();});
    connect(buttons.button(QDialogButtonBox::Reset),&QPushButton::clicked,&dialog,[&]{working.blend=ImageBlendMode::Normal;working.opacity=working.fillOpacity=1;working.channels=7;working.blendIfChannel=ImageBlendIfChannel::Gray;for(auto &range:working.blendIfSource)range={0,0,1,1};for(auto &range:working.blendIfBackdrop)range={0,0,1,1};{const QSignalBlocker b(blend),o(opacity),f(fill),c(channel);blend->setCurrentIndex(0);opacity->setValue(100);fill->setValue(100);channel->setCurrentIndex(0);}for(auto *box:enabledChannels){const QSignalBlocker guard(box);box->setChecked(true);}refreshRanges();applyPreview();});
    refreshRanges();doc->beginEdit(tr("混合选项"));if(dialog.exec()==QDialog::Accepted){doc->updateLayer(working);doc->commitEdit();}else doc->cancelEdit();canvas->invalidateDocumentPreview();updateProperties();
}
void ImageEditorWindow::transformLayerValues(){const QRect bounds(layerX_->value(),layerY_->value(),layerWidth_->value(),layerHeight_->value());canvas_->cancelGesture();QString error;if(!document_->transformLayer(tools_->layer(),bounds,&error))QMessageBox::warning(this,tr("图层变换"),error);updateProperties();canvas_->update();}
void ImageEditorWindow::editTextLayer(const QUuid &id) {
    const auto layer=activeLayer(document_,id);if(layer.text.isEmpty() || layer.locked)return;
    QDialog dialog(this);dialog.setObjectName("imageEditorTextDialog");dialog.setWindowTitle(tr("编辑文字"));dialog.setPalette(palette());dialog.setAttribute(Qt::WA_WindowPropagation,true);
    QFormLayout form(&dialog);QPlainTextEdit text(layer.text);text.setObjectName("imageEditorEditText");form.addRow(tr("文字"),&text);
    QFontComboBox font;font.setCurrentFont(layer.textFont);form.addRow(tr("字体"),&font);
    QSpinBox size;size.setObjectName("imageEditorEditTextSize");size.setRange(1,512);size.setValue(layer.textFont.pixelSize());form.addRow(tr("字号(px)"),&size);
    QCheckBox bold(tr("加粗")),italic(tr("斜体"));bold.setObjectName("imageEditorEditTextBold");italic.setObjectName("imageEditorEditTextItalic");bold.setChecked(layer.textFont.bold());italic.setChecked(layer.textFont.italic());form.addRow(&bold,&italic);
    QDoubleSpinBox spacing;spacing.setObjectName("imageEditorEditTextSpacing");spacing.setRange(.2,10);spacing.setSingleStep(.1);spacing.setValue(layer.textLineSpacing);form.addRow(tr("行距(倍)"),&spacing);
    QDialogButtonBox buttons(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);form.addRow(&buttons);connect(&buttons,&QDialogButtonBox::accepted,&dialog,&QDialog::accept);connect(&buttons,&QDialogButtonBox::rejected,&dialog,&QDialog::reject);
    dialog.resize(460,340);if(dialog.exec()!=QDialog::Accepted)return;
    auto chosen=font.currentFont();chosen.setPixelSize(size.value());chosen.setBold(bold.isChecked());chosen.setItalic(italic.isChecked());tools_->editText(id,text.toPlainText(),chosen,spacing.value());
}
void ImageEditorWindow::renameLayer(){auto l=activeLayer(document_,tools_->layer());if(l.id.isNull())return;bool ok;const auto name=QInputDialog::getText(this,tr("图层名称"),tr("名称"),QLineEdit::Normal,l.name,&ok);if(ok&&!name.trimmed().isEmpty()){l.name=name;document_->updateLayer(l,tr("重命名图层"));}}
void ImageEditorWindow::reorderLayer(int direction){const auto source=document_->layers();for(int i=0;i<source.size();++i)if(source[i].id==tools_->layer()){for(int target=i+direction;target>=0&&target<source.size();target+=direction)if(source[target].parentId==source[i].parentId){document_->moveLayer(tools_->layer(),target);break;}break;}}
void ImageEditorWindow::selectAll(){canvas_->cancelGesture();QPainterPath path;path.addRect(QRectF(QPointF(),document_->size()));tools_->selectPath(path,ImageSelectionMode::Replace);}
void ImageEditorWindow::newImage(){QDialog dialog(this);dialog.setAttribute(Qt::WA_WindowPropagation,true);dialog.setPalette(palette());dialog.setWindowTitle(tr("新建图像"));QFormLayout form(&dialog);QSpinBox w,h;w.setRange(1,1000000);h.setRange(1,1000000);w.setValue(1920);h.setValue(1080);QComboBox precision;precision.addItems({tr("8 位"),tr("16 位"),tr("32 位浮点(HDR)")});form.addRow(tr("宽度(px)"),&w);form.addRow(tr("高度(px)"),&h);form.addRow(tr("精度"),&precision);QDialogButtonBox buttons(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);form.addRow(&buttons);connect(&buttons,&QDialogButtonBox::accepted,&dialog,&QDialog::accept);connect(&buttons,&QDialogButtonBox::rejected,&dialog,&QDialog::reject);if(dialog.exec()==QDialog::Accepted){auto *doc=new ImageDocument({w.value(),h.value()},ImagePrecision(precision.currentIndex()));doc->setColorSpace(QColorSpace::SRgb);doc->addLayer(tr("图层 1"));doc->history()->clear();doc->history()->setClean();addDocument(doc,tr("未命名"));}}
void ImageEditorWindow::openImage(){
    const auto path=QFileDialog::getOpenFileName(this,tr("打开图像"),QFileInfo(sourcePath_).absolutePath(),tr("图像 (*.png *.jpg *.jpeg *.webp *.avif *.tif *.tiff *.bmp *.psd *.psb);;所有文件 (*)"));if(path.isEmpty())return;for(int i=0;i<pages_.size();++i)if(QFileInfo(pages_[i].path).absoluteFilePath().compare(QFileInfo(path).absoluteFilePath(),Qt::CaseInsensitive)==0){activateDocument(i);return;}
    const auto suffix=QFileInfo(path).suffix().toLower();if(suffix!="psd" && suffix!="psb"){
        auto *decoder=new PlayerImage(qApp);QPointer<ImageEditorWindow> owner(this);statusBar()->showMessage(tr("正在读取图像…"));
        connect(decoder,&PlayerImage::loaded,qApp,[owner,path,decoder](const QImage &image){decoder->deleteLater();if(!owner)return;owner->updateStatus();owner->addImage(image,path);});
        connect(decoder,&PlayerImage::failed,qApp,[owner,decoder](const QString &error){decoder->deleteLater();if(owner){owner->updateStatus();QMessageBox::warning(owner,tr("打开图像"),error);}});decoder->open(path);return;
    }
    struct Result{std::unique_ptr<ImageDocument> document;QString error;QStringList warnings;};auto result=std::make_shared<Result>();QPointer<ImageEditorWindow> owner(this);statusBar()->showMessage(tr("正在读取图像…"));
    auto *thread=QThread::create([path,result]{result->document=ImagePsd::load(path,&result->error,&result->warnings);if(result->document){const auto size=result->document->size();result->document->compositePreview(QRect(QPoint(),size),size.scaled({640,900},Qt::KeepAspectRatio));result->error=result->document->storageError();result->document->moveToThread(qApp->thread());}});
    connect(thread,&QThread::finished,qApp,[owner,result,path]{if(!owner)return;owner->updateStatus();if(!result->error.isEmpty()){QMessageBox::warning(owner,tr("打开图像"),result->error);return;}owner->addDocument(result->document.release(),path);if(!result->warnings.isEmpty())QMessageBox::information(owner,tr("PSD 导入说明"),result->warnings.join('\n'));});connect(thread,&QThread::finished,thread,&QObject::deleteLater);thread->start();
}
bool ImageEditorWindow::isSourcePath(const QString &path) const{const auto absolute=QFileInfo(path).absoluteFilePath();for(const auto &page:pages_)if(!page.path.isEmpty()&&absolute.compare(QFileInfo(page.path).absoluteFilePath(),Qt::CaseInsensitive)==0)return true;return false;}
void ImageEditorWindow::exportDocument(bool floating) {
    canvas_->cancelGesture();
    const auto path=QFileDialog::getSaveFileName(this,floating?tr("导出浮点 TIFF"):tr("另存图层工程"),QFileInfo(sourcePath_).absolutePath()+"/"+QFileInfo(sourcePath_).completeBaseName()+(floating?"-edited.tif":"-edited.psd"),floating?tr("TIFF (*.tif *.tiff)"):tr("Photoshop PSD (*.psd);;Photoshop PSB (*.psb)"));
    if(path.isEmpty())return;
    if(isSourcePath(path)){QMessageBox::warning(this,tr("导出图像"),tr("请选择新路径以保留源文件。"));return;}
    auto snapshot=std::shared_ptr<ImageDocument>(document_->snapshot().release());const auto revision=document_->revision();QPointer<ImageDocument> exportingDocument(document_);auto result=std::make_shared<QString>();
    auto *thread=QThread::create([snapshot,path,floating,result]() mutable {if(floating)ImageHdr::exportFloatTiff(snapshot.get(),path,result.get());else *result=ImagePsd::save(snapshot.get(),path);snapshot.reset();});snapshot->moveToThread(thread);
    auto *saveAction=findChild<QAction *>(floating?"imageEditorExportFloat":"imageEditorSavePsd");saveAction->setEnabled(false);statusBar()->showMessage(tr("正在后台保存图像…"));
    connect(thread,&QThread::finished,this,[this,result,revision,floating,saveAction,exportingDocument]{saveAction->setEnabled(true);if(!result->isEmpty())QMessageBox::warning(this,tr("保存图像"),*result);else{if(!floating && exportingDocument && exportingDocument->revision()==revision)exportingDocument->history()->setClean();statusBar()->showMessage(tr("图像已保存。"),5000);}});
    connect(thread,&QThread::finished,thread,&QObject::deleteLater);snapshot.reset();thread->start();
}
void ImageEditorWindow::savePng(){canvas_->cancelGesture();const auto path=QFileDialog::getSaveFileName(this,tr("导出扁平 PNG(不含图层和历史)"),QFileInfo(sourcePath_).absolutePath()+"/"+QFileInfo(sourcePath_).completeBaseName()+"-edited.png",tr("PNG (*.png)"));if(path.isEmpty())return;if(isSourcePath(path)){QMessageBox::warning(this,tr("导出图像"),tr("请选择新路径，避免覆盖源文件。"));return;}const auto error=ImageEditorTools::savePng(document_,path);if(!error.isEmpty())QMessageBox::warning(this,tr("PNG 导出"),error);else statusBar()->showMessage(tr("已导出扁平 PNG；图层与历史保留在窗口中。"),5000);}
void ImageEditorWindow::closeEvent(QCloseEvent *event){QStringList unsaved;for(const auto &page:pages_){page.canvas->cancelGesture();if(!page.document->history()->isClean())unsaved.append(QFileInfo(page.path).fileName());}if(!unsaved.isEmpty()&&QMessageBox::question(this,tr("关闭图像编辑"),tr("以下文档有未保存的图层与编辑：\n%1\n确定关闭？").arg(unsaved.join("\n")),QMessageBox::Yes|QMessageBox::No,QMessageBox::No)!=QMessageBox::Yes){event->ignore();return;}event->accept();}

void ImageEditorWindow::adjustImage(int value){
    canvas_->cancelGesture();const auto layer=activeLayer(document_,tools_->layer());if(layer.id.isNull()||layer.group||layer.locked){QMessageBox::warning(this,tr("图像调整"),tr("请先选择未锁定的像素图层。"));return;}
    if(tools_->editingMask()){QMessageBox::warning(this,tr("图像调整"),tr("颜色调整作用于像素图层。请先取消“编辑蒙版”，再调整图层颜色。"));return;}
    ImageAdjustmentSpec spec;spec.kind=ImageAdjustmentKind(value);const QStringList labels{tr("曝光"),tr("亮度 / 对比度"),tr("色阶"),tr("曲线"),tr("色相 / 饱和度"),tr("色彩平衡"),tr("通道混合器"),tr("反相"),tr("灰度"),tr("阈值"),tr("色调分离"),tr("高斯模糊"),tr("USM 锐化"),tr("中值降噪"),tr("边缘检测")};const auto label=labels.value(value,tr("图像调整"));
    const bool immediate=spec.kind==ImageAdjustmentKind::Invert||spec.kind==ImageAdjustmentKind::Grayscale||spec.kind==ImageAdjustmentKind::EdgeDetect;
    if(!immediate){
        QDialog dialog(this);dialog.setAttribute(Qt::WA_WindowPropagation,true);dialog.setPalette(palette());dialog.setObjectName("imageEditorAdjustmentDialog");dialog.setWindowTitle(label);dialog.resize(spec.kind==ImageAdjustmentKind::Curves?540:410,300);QVBoxLayout layout(&dialog);auto *form=new QFormLayout;layout.addLayout(form);QList<QPair<QDoubleSpinBox *,double *>> fields;QList<QPair<QSpinBox *,int *>> integers;QList<QTableWidget *> curves;
        auto number=[&](const QString &name,const QString &object,double &value,double min,double max){auto *spin=new QDoubleSpinBox(&dialog);spin->setObjectName(object);spin->setRange(min,max);spin->setDecimals(4);spin->setValue(value);spin->setSingleStep(.1);form->addRow(name,spin);fields.append({spin,&value});};
        auto integer=[&](const QString &name,int &value,int min,int max){auto *spin=new QSpinBox(&dialog);spin->setRange(min,max);spin->setValue(value);form->addRow(name,spin);integers.append({spin,&value});};
        switch(spec.kind){
        case ImageAdjustmentKind::Exposure:number(tr("曝光(EV)"),"exposure",spec.exposure,-20,20);break;
        case ImageAdjustmentKind::BrightnessContrast:number(tr("亮度"),"brightness",spec.brightness,-10,10);number(tr("对比度"),"contrast",spec.contrast,-1,10);break;
        case ImageAdjustmentKind::Levels:number(tr("输入黑点"),"inputBlack",spec.inputBlack,-100,100);number(tr("输入白点"),"inputWhite",spec.inputWhite,-100,100);number(tr("中间调 Gamma"),"gamma",spec.gamma,.01,100);number(tr("输出黑点"),"outputBlack",spec.outputBlack,-100,100);number(tr("输出白点"),"outputWhite",spec.outputWhite,-100,100);break;
        case ImageAdjustmentKind::Curves:{auto *tabs=new QTabWidget(&dialog);const QStringList channels{tr("RGB"),tr("红"),tr("绿"),tr("蓝")};for(int c=0;c<4;++c){auto *page=new QWidget(tabs);auto *column=new QVBoxLayout(page);auto *plot=new QLabel(page);plot->setFixedHeight(110);column->addWidget(plot);auto *table=new QTableWidget(5,2,page);table->setObjectName("imageEditorCurve_"+QString::number(c));table->setHorizontalHeaderLabels({tr("输入"),tr("输出")});for(int row=0;row<5;++row)for(int col=0;col<2;++col)table->setItem(row,col,new QTableWidgetItem(QString::number(row*.25)));column->addWidget(table);auto redraw=[table,plot]{QPixmap image(460,110);image.fill(QColor("#383838"));QPainter p(&image);p.setPen(QColor("#444"));for(int x=0;x<=4;++x)p.drawLine(x*114,0,x*114,109);for(int y=0;y<=4;++y)p.drawLine(0,y*27,459,y*27);p.setPen(QPen(QColor("#ddd"),2));QPolygonF points;for(int row=0;row<table->rowCount();++row){const auto *a=table->item(row,0),*b=table->item(row,1);if(a&&b)points<<QPointF(a->text().toDouble()*459,(1-b->text().toDouble())*109);}p.drawPolyline(points);plot->setPixmap(image);};connect(table,&QTableWidget::cellChanged,page,[redraw](int,int){redraw();});auto *row=new QHBoxLayout;auto *add=new QPushButton(tr("添加控制点"),page),*remove=new QPushButton(tr("删除控制点"),page);row->addWidget(add);row->addWidget(remove);column->addLayout(row);connect(add,&QPushButton::clicked,page,[table]{const int row=table->currentRow()<0?table->rowCount():table->currentRow()+1;table->insertRow(row);table->setItem(row,0,new QTableWidgetItem("0.5"));table->setItem(row,1,new QTableWidgetItem("0.5"));});connect(remove,&QPushButton::clicked,page,[table]{if(table->currentRow()>=0)table->removeRow(table->currentRow());});curves.append(table);redraw();tabs->addTab(page,channels[c]);}layout.addWidget(tabs);layout.addWidget(new QLabel(tr("输入点必须递增；HDR 超出范围使用端点斜率外推。"),&dialog));break;}
        case ImageAdjustmentKind::HueSaturation:number(tr("色相(度)"),"hue",spec.hue,-360,360);number(tr("饱和度倍率"),"saturation",spec.saturation,0,10);number(tr("明度"),"lightness",spec.lightness,-10,10);break;
        case ImageAdjustmentKind::ColorBalance:number(tr("红色增益"),"redGain",spec.redGain,0,10);number(tr("绿色增益"),"greenGain",spec.greenGain,0,10);number(tr("蓝色增益"),"blueGain",spec.blueGain,0,10);break;
        case ImageAdjustmentKind::ChannelMixer:{const QStringList channel{tr("红"),tr("绿"),tr("蓝")};for(int row=0;row<3;++row)for(int column=0;column<3;++column)number(tr("输出 %1 ← 输入 %2").arg(channel[row],channel[column]),QString("mix_%1_%2").arg(row).arg(column),spec.channelMixer[row][column],-10,10);break;}
        case ImageAdjustmentKind::Threshold:number(tr("阈值"),"threshold",spec.threshold,-100,100);break;
        case ImageAdjustmentKind::Posterize:integer(tr("色阶数"),spec.posterizeLevels,2,65536);break;
        case ImageAdjustmentKind::GaussianBlur:integer(tr("半径(px)"),spec.radius,1,64);break;
        case ImageAdjustmentKind::UnsharpMask:integer(tr("半径(px)"),spec.radius,1,64);number(tr("强度"),"amount",spec.amount,0,20);break;
        case ImageAdjustmentKind::Median:integer(tr("半径(px)"),spec.radius,1,8);break;
        default:break;
        }
        if(spec.kind==ImageAdjustmentKind::Levels||spec.kind==ImageAdjustmentKind::Curves){const auto sampled=document_->compositePreview(QRect(QPoint(),document_->size()),{256,128});const auto bins=ImageAdjustments::histogram(sampled);QPixmap plot(360,72);plot.fill(QColor("#383838"));QPainter p(&plot);const QList<QColor> colors{QColor("#c55"),QColor("#5c5"),QColor("#59d")};for(int channel=0;channel<3;++channel){const auto maximum=*std::max_element(bins[channel].begin(),bins[channel].end());p.setPen(colors[channel]);QPolygonF path;for(int x=0;x<bins[channel].size();++x)path<<QPointF(double(x)*359/(bins[channel].size()-1),71-(maximum?double(bins[channel][x])*70/maximum:0));p.drawPolyline(path);}auto *histogram=new QLabel(&dialog);histogram->setPixmap(plot);histogram->setToolTip(tr("采样直方图(256×128 合成预览)"));layout.addWidget(histogram);}
        layout.addWidget(new QLabel(tr("应用于当前像素图层与选区；保持原位深和 Alpha。"),&dialog));QDialogButtonBox buttons(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);layout.addWidget(&buttons);connect(&buttons,&QDialogButtonBox::rejected,&dialog,&QDialog::reject);connect(&buttons,&QDialogButtonBox::accepted,&dialog,[&]{for(const auto &[spin,value]:fields)*value=spin->value();for(const auto &[spin,value]:integers)*value=spin->value();for(int channel=0;channel<curves.size();++channel){spec.curves[channel].clear();auto *table=curves[channel];for(int row=0;row<table->rowCount();++row){bool xOk=false,yOk=false;const auto *a=table->item(row,0),*b=table->item(row,1);const double x=a?a->text().toDouble(&xOk):0,y=b?b->text().toDouble(&yOk):0;if(!xOk||!yOk){QMessageBox::warning(&dialog,tr("曲线"),tr("控制点必须是有效数字。"));return;}spec.curves[channel].append({x,y});}}QString error;if(!ImageAdjustments::validate(spec,&error)){QMessageBox::warning(&dialog,label,error);return;}dialog.accept();});if(dialog.exec()!=QDialog::Accepted)return;
    }
    QString error;if(!ImageAdjustments::apply(document_,layer.id,spec,label,&error))QMessageBox::warning(this,label,error);
}
}
