#include "image/ImageDocument.h"
#include <QTest>
#include <cmath>
#include <cstring>
using namespace vsr;
namespace {
QImage pixels(ImagePrecision precision,QSize size={3,2}){
    const auto format=precision==ImagePrecision::Float32?QImage::Format_RGBA32FPx4:precision==ImagePrecision::UInt16?QImage::Format_RGBA64:QImage::Format_RGBA8888;QImage image(size,format);image.setColorSpace(QColorSpace::SRgbLinear);
    for(int y=0;y<size.height();++y)for(int x=0;x<size.width();++x){if(precision==ImagePrecision::Float32){auto *p=reinterpret_cast<float *>(image.scanLine(y))+x*4;p[0]=-.25f+x*.2f;p[1]=12.5f+y*.3f;p[2]=1.00001f;p[3]=x?.4f:0.f;}else if(precision==ImagePrecision::UInt16){auto *p=reinterpret_cast<quint16 *>(image.scanLine(y))+x*4;p[0]=quint16(12001+x);p[1]=quint16(40003+y);p[2]=123;p[3]=x?54321:0;}else{auto *p=image.scanLine(y)+x*4;p[0]=uchar(17+x);p[1]=uchar(93+y);p[2]=201;p[3]=x?193:0;}}
    return image;
}
bool sameComposite(const QImage &actual,const QImage &expected){
    if(actual.size()!=expected.size() || actual.format()!=expected.format())return false;
    if(actual.format()!=QImage::Format_RGBA32FPx4)return actual==expected;
    for(int y=0;y<actual.height();++y){const auto *a=reinterpret_cast<const float *>(actual.constScanLine(y)),*b=reinterpret_cast<const float *>(expected.constScanLine(y));for(int x=0;x<actual.width()*4;++x)if(std::abs(a[x]-b[x])>1e-5f)return false;}return true;
}
}
class TestImageLayerOperations final : public QObject {
    Q_OBJECT
private slots:
    void transformNativePrecisionAndMask(){
        for(auto precision:{ImagePrecision::UInt8,ImagePrecision::UInt16,ImagePrecision::Float32}){
            ImageDocument doc({100,100},precision);doc.setColorSpace(QColorSpace::SRgbLinear);const auto source=pixels(precision);const auto id=doc.addLayer("Native",source,{4,5});QImage mask(3,2,QImage::Format_Grayscale16);for(int y=0;y<2;++y)for(int x=0;x<3;++x)reinterpret_cast<quint16 *>(mask.scanLine(y))[x]=quint16(123+x*10001+y);doc.writeMask(id,{},mask);doc.history()->clear();QString error;
            QVERIFY2(doc.flipLayer(id,true,&error),qPrintable(error));QCOMPARE(doc.readRegion(id,{0,0,3,2}),source.mirrored(true,false));QCOMPARE(doc.maskRegion(id,{0,0,3,2}),mask.mirrored(true,false));QCOMPARE(doc.history()->count(),1);doc.history()->undo();QCOMPARE(doc.readRegion(id,{0,0,3,2}),source);QCOMPARE(doc.maskRegion(id,{0,0,3,2}),mask);
            QVERIFY2(doc.rotateLayer(id,1,&error),qPrintable(error));QCOMPARE(doc.layerBounds(id).size(),QSize(2,3));const auto rotated=doc.readRegion(id,{0,0,2,3}),rotatedMask=doc.maskRegion(id,{0,0,2,3});const int bytes=source.depth()/8;for(int y=0;y<3;++y)for(int x=0;x<2;++x){QVERIFY(std::memcmp(rotated.constScanLine(y)+x*bytes,source.constScanLine(1-x)+y*bytes,bytes)==0);QCOMPARE(reinterpret_cast<const quint16 *>(rotatedMask.constScanLine(y))[x],reinterpret_cast<const quint16 *>(mask.constScanLine(1-x))[y]);}doc.history()->undo();QCOMPARE(doc.readRegion(id,{0,0,3,2}),source);
            doc.beginEdit("Tentative transform");QVERIFY(doc.transformLayer(id,{10,11,6,4},&error));QCOMPARE(doc.history()->index(),0);doc.cancelEdit();QCOMPARE(doc.layers().first().offset,QPoint(4,5));QCOMPARE(doc.readRegion(id,{0,0,3,2}),source);
        }
    }
    void groupTransformAndLockedDescendant(){
        ImageDocument doc({100,100},ImagePrecision::Float32);doc.setColorSpace(QColorSpace::SRgbLinear);const auto group=doc.addLayer("Group");auto info=doc.layers().last();info.group=true;doc.updateLayer(info);const auto first=doc.addLayer("First",pixels(ImagePrecision::Float32,{2,2}),{1,2});info=doc.layers().last();info.parentId=group;doc.updateLayer(info);const auto second=doc.addLayer("Second",pixels(ImagePrecision::Float32,{2,2}),{5,4});info=doc.layers().last();info.parentId=group;doc.updateLayer(info);QImage mask(1,1,QImage::Format_Grayscale16);mask.fill(Qt::black);doc.writeMask(group,{1,2},mask);doc.history()->clear();QString error;
        QVERIFY2(doc.transformLayer(group,{10,20,12,8},&error),qPrintable(error));const auto layers=doc.layers();QCOMPARE(layers[1].offset,QPoint(10,20));QCOMPARE(layers[2].offset,QPoint(18,24));QCOMPARE(doc.layerBounds(first).size(),QSize(4,4));QCOMPARE(doc.layerBounds(second).size(),QSize(4,4));QCOMPARE(doc.maskBounds(group),QRect(0,0,2,2));QCOMPARE(reinterpret_cast<const quint16 *>(doc.maskRegion(group,{0,0,1,1}).constBits())[0],quint16(28672));doc.history()->undo();QCOMPARE(doc.layers()[1].offset,QPoint(1,2));QCOMPARE(doc.maskBounds(group),QRect(1,2,1,1));
        info=doc.layers().last();info.locked=true;doc.updateLayer(info);const auto before=doc.layers();QVERIFY(!doc.transformLayer(group,{0,0,3,2},&error));QVERIFY(!error.isEmpty());QCOMPARE(doc.layers()[1].offset,before[1].offset);QCOMPARE(doc.layerBounds(first).size(),QSize(2,2));
    }
    void mergeUndoAndMasks(){
        for(auto precision:{ImagePrecision::UInt16,ImagePrecision::Float32}){
            ImageDocument doc({20,20},precision);doc.setColorSpace(QColorSpace::SRgbLinear);auto image=pixels(precision,{2,2});const auto bottom=doc.addLayer("Bottom",image,{3,4});const auto top=doc.addLayer("Top",image,{3,4});auto info=doc.layers().last();info.opacity=.5;doc.updateLayer(info);QImage mask(2,2,QImage::Format_Grayscale16);mask.fill(Qt::white);reinterpret_cast<quint16 *>(mask.bits())[0]=123;doc.writeMask(top,{},mask);const auto expected=doc.composite({0,0,20,20});doc.history()->clear();QString error;QCOMPARE(doc.mergeDown(top,&error),bottom);QCOMPARE(doc.layers().size(),1);QVERIFY(sameComposite(doc.composite({0,0,20,20}),expected));QCOMPARE(doc.history()->count(),1);doc.history()->undo();QCOMPARE(doc.layers().size(),2);QCOMPARE(doc.maskRegion(top,{0,0,2,2}),mask);QCOMPARE(doc.composite({0,0,20,20}),expected);doc.history()->redo();QCOMPARE(doc.layers().size(),1);
        }
        ImageDocument doc({10,10},ImagePrecision::UInt8);doc.addLayer("Bottom",pixels(ImagePrecision::UInt8));const auto top=doc.addLayer("Top",pixels(ImagePrecision::UInt8));auto info=doc.layers().last();info.blend=ImageBlendMode::Multiply;doc.updateLayer(info);QString error;QVERIFY(doc.mergeDown(top,&error).isNull());QVERIFY(!error.isEmpty());QCOMPARE(doc.layers().size(),2);
    }
    void giantLazyTransformIsBounded(){
        ImageDocument doc({100000,100000},ImagePrecision::Float32);int reads=0;QSize largest;
        const auto id=doc.addLazyLayer("Giant",{100000,100000},{},[&](const QRect &r){++reads;if(r.width()>largest.width() || r.height()>largest.height())largest=r.size();QImage image(r.size(),QImage::Format_RGBA32FPx4);for(int y=0;y<image.height();++y){auto *p=reinterpret_cast<float *>(image.scanLine(y));for(int x=0;x<image.width();++x){p[x*4]=-.25f;p[x*4+1]=12.5f;p[x*4+2]=1.f;p[x*4+3]=1.f;}}return image;});doc.history()->clear();QString error;
        QVERIFY(doc.transformLayer(id,{100,200,100000,100000},&error));QCOMPARE(reads,0);QCOMPARE(doc.layers().first().offset,QPoint(100,200));QVERIFY(doc.transformLayer(id,{0,0,50000,50000},&error));QCOMPARE(reads,0);const auto region=doc.readRegion(id,{0,0,4,4});QVERIFY(!region.isNull());QVERIFY(reads>0);QVERIFY(largest.width()<=ImageDocument::TileSize && largest.height()<=ImageDocument::TileSize);QCOMPARE(reinterpret_cast<const float *>(region.constBits())[0],-.25f);QCOMPARE(reinterpret_cast<const float *>(region.constBits())[1],12.5f);doc.history()->undo();QCOMPARE(doc.layerBounds(id).size(),QSize(100000,100000));
        const auto another=doc.addLazyLayer("Other giant",{100000,100000},{},[&](const QRect &r){++reads;QImage image(r.size(),QImage::Format_RGBA32FPx4);image.fill(Qt::red);return image;});const int beforeMerge=reads;QVERIFY(!doc.mergeDown(another,&error).isNull());QCOMPARE(reads,beforeMerge);QVERIFY(!doc.compositePreview({0,0,100000,100000},{4,4}).isNull());
    }
    void advancedBlendingAndUndo(){
        ImageDocument doc({1,1},ImagePrecision::Float32);QImage bottom(1,1,QImage::Format_RGBA32FPx4),top(1,1,QImage::Format_RGBA32FPx4);float b[]={.1f,.2f,.3f,1},s[]={.5f,.25f,.75f,1};std::memcpy(bottom.bits(),b,sizeof b);std::memcpy(top.bits(),s,sizeof s);doc.addLayer("Backdrop",bottom);const auto id=doc.addLayer("Source",top);doc.history()->clear();auto info=doc.layers().last();info.fillOpacity=.5f;info.opacity=.5f;doc.updateLayer(info);auto result=doc.composite({0,0,1,1});const auto *p=reinterpret_cast<const float *>(result.constBits());QVERIFY(std::abs(p[0]-.2f)<1e-6f);QVERIFY(std::abs(p[2]-.4125f)<1e-6f);
        info.fillOpacity=info.opacity=1;info.channels=6;info.blendIfSource[1]={0,1,1,1};info.blendIfBackdrop[2]={0,.4f,1,1};doc.updateLayer(info);result=doc.composite({0,0,1,1});p=reinterpret_cast<const float *>(result.constBits());QCOMPARE(p[0],.1f);QVERIFY(std::abs(p[1]-.2125f)<1e-6f);QVERIFY(std::abs(p[2]-.4125f)<1e-6f);QCOMPARE(doc.readRegion(id,{0,0,1,1}),top);doc.history()->undo();QCOMPARE(doc.layers().last().channels,quint8(7));QCOMPARE(doc.layers().last().fillOpacity,.5f);doc.history()->redo();QCOMPARE(doc.layers().last().blendIfSource[1],(ImageBlendRange{0,1,1,1}));
        QString error;const int historyIndex=doc.history()->index();QVERIFY(doc.mergeDown(id,&error).isNull());QVERIFY(!error.isEmpty());QCOMPARE(doc.history()->index(),historyIndex);QCOMPARE(doc.composite({0,0,1,1}),result);info.channels=7;info.blendIfBackdrop=ImageLayerInfo{}.blendIfBackdrop;info.fillOpacity=.4f;doc.updateLayer(info);const auto beforeMerge=doc.composite({0,0,1,1});QVERIFY(!doc.mergeDown(id,&error).isNull());QVERIFY(sameComposite(doc.composite({0,0,1,1}),beforeMerge));QCOMPARE(doc.layers().first().fillOpacity,1.f);QCOMPARE(doc.layers().first().blendIfSource,ImageLayerInfo{}.blendIfSource);doc.history()->undo();QCOMPARE(doc.layers().last().fillOpacity,.4f);QCOMPARE(doc.layers().last().blendIfSource[1],(ImageBlendRange{0,1,1,1}));
    }
    void qualityAcrossTileBoundary(){
        ImageDocument doc({512,1},ImagePrecision::Float32);QImage image(2,1,QImage::Format_RGBA32FPx4);float values[]={-1,10,0,.5f,1,0,4,1};std::memcpy(image.bits(),values,sizeof values);const auto id=doc.addLayer("Edge",image,{255,0});const auto result=doc.compositePreview({255,0,2,1},{1,1},ImageSamplingQuality::Bilinear);const auto *p=reinterpret_cast<const float *>(result.constBits());QVERIFY(std::abs(p[0]-1.f/3)<1e-5f);QVERIFY(std::abs(p[1]-10.f/3)<1e-5f);QVERIFY(std::abs(p[2]-8.f/3)<1e-5f);QCOMPARE(p[3],.75f);QImage mask(2,1,QImage::Format_Grayscale16);auto *m=reinterpret_cast<quint16 *>(mask.bits());m[0]=0;m[1]=65535;doc.writeMask(id,{},mask);QCOMPARE(reinterpret_cast<const quint16 *>(doc.maskPreview(id,{0,0,2,1},{1,1},ImageSamplingQuality::Bilinear).constBits())[0],quint16(32768));
        ImageDocument lazy({100000,100000},ImagePrecision::Float32);int nativeReads=0,qualityReads=0;const auto lazyId=lazy.addLazyLayer("Quality source",lazy.size(),{},[&](const QRect &r){++nativeReads;QImage out(r.size(),QImage::Format_RGBA32FPx4);out.fill(Qt::red);return out;},{},[&](const QRect &,QSize size,ImageSamplingQuality quality){++qualityReads;Q_ASSERT(quality==ImageSamplingQuality::Bilinear);QImage out(size,QImage::Format_RGBA32FPx4);out.fill(Qt::red);return out;});QCOMPARE(lazy.compositePreview({0,0,100000,100000},{2,2},ImageSamplingQuality::Bilinear).pixelColor(0,0),QColor(Qt::red));QCOMPARE(nativeReads,0);QCOMPARE(qualityReads,1);QImage patch(1,1,QImage::Format_RGBA32FPx4);patch.fill(Qt::green);lazy.writeRegion(lazyId,{},patch);const int before=nativeReads;const auto edited=lazy.compositePreview({0,0,2,1},{1,1},ImageSamplingQuality::Bilinear);const auto *e=reinterpret_cast<const float *>(edited.constBits());QCOMPARE(e[0],.5f);QCOMPARE(e[1],.5f);QCOMPARE(nativeReads,before);
    }
    void lazyGroupMergeVisibleAndFlatten(){
        ImageDocument doc({100000,100000},ImagePrecision::Float32);int reads=0;QSize largest;auto reader=[&](const QRect &r){++reads;largest.setWidth(std::max(largest.width(),r.width()));largest.setHeight(std::max(largest.height(),r.height()));QImage out(r.size(),QImage::Format_RGBA32FPx4);out.fill(QColor(255,0,0,128));return out;};const auto id=doc.addLazyLayer("Giant",doc.size(),{},reader);QString error;const auto group=doc.groupLayer(id,"Group",&error);QVERIFY2(!group.isNull(),qPrintable(error));QCOMPARE(reads,0);QCOMPARE(doc.layers().last().parentId,group);const auto hidden=doc.addLayer("Hidden");auto info=doc.layers().last();info.visible=false;doc.updateLayer(info);doc.history()->clear();const auto merged=doc.mergeVisible(&error);QVERIFY2(!merged.isNull(),qPrintable(error));QCOMPARE(reads,0);QCOMPARE(doc.layers().size(),2);QCOMPARE(doc.layers().first().id,hidden);QVERIFY(!doc.readRegion(merged,{0,0,2,2}).isNull());QVERIFY(largest.width()<=ImageDocument::TileSize && largest.height()<=ImageDocument::TileSize);doc.history()->undo();QCOMPARE(doc.layers().size(),3);const int before=reads;const auto flat=doc.flatten(&error);QVERIFY2(!flat.isNull(),qPrintable(error));QCOMPARE(reads,before);QCOMPARE(doc.layers().size(),1);QVERIFY(doc.layers().first().locked);const auto whiteComposite=doc.readRegion(flat,{0,0,1,1});const auto *p=reinterpret_cast<const float *>(whiteComposite.constBits());QCOMPARE(p[0],1.f);QVERIFY(p[1]>.49f && p[1]<.51f);QCOMPARE(p[3],1.f);doc.history()->undo();QCOMPARE(doc.layers().size(),3);
    }
};
QTEST_MAIN(TestImageLayerOperations)
#include "TestImageLayerOperations.moc"
