#pragma once
#include "player/PlayerAudioMetadata.h"
#include "backend/ThreeFpApi.h"
#include "backend/VapourSynthFrameServer.h"
#include <QMainWindow>
#include <QJsonObject>
#include <memory>
#include <QPointer>
#include <QElapsedTimer>
#include "player/PlayerResources.h"
class QSlider;
class QSettings;
class QLineEdit;
class QDoubleSpinBox;
class QPushButton;
class QLabel;
class QTimer;
class QVBoxLayout;
class QSplitter;
class QTreeWidget;
class QTreeWidgetItem;
class TestPlayer;
namespace vsr {
class ThreeFpPlayer;
class LavPlayback;
class PreviewPane;
class ChapterTimeline;
class PlayerSubtitles;
class PlayerNetworkInput;
class PlayerLanguage;
class PlayerImage;
class PlayerImageTools;
class PlayerInfoPanel;
class PlayerDiscMenu;
class PlayerWindow final : public QMainWindow {
    Q_OBJECT
public:
    PlayerWindow();
    ~PlayerWindow() override;
    bool openFile(const QString &path);
    bool openFolder(const QString &path);
    void loadPreset(const QString &path);
    void setInterpolation(int stage, bool automatic = false, int renderer = 0);
    int interpolationStage() const;
    void togglePlayback();
    void seekTime(qint64 time);
    void seekFrame(qint64 frame);
    void setRate(double rate);
    qint64 position() const;
    ThreeFpSnapshot snapshot() const;
    ThreeFpSnapshot outputSnapshot() const;
    static double normalizedRate(double rate);
    quint64 skippedFrames() const { return skippedFrames_; }
    int qualityStage() const { return qualityStage_; }
    bool saveConfiguration(const QString &path);
    bool loadConfiguration(const QString &path);
    void toggleFullscreen();
protected:
    bool eventFilter(QObject *, QEvent *) override;
    void dragEnterEvent(QDragEnterEvent *) override;
    void dropEvent(QDropEvent *) override;
    void dragMoveEvent(QDragMoveEvent *) override;
    void dragLeaveEvent(QDragLeaveEvent *) override;
private:
    friend class ::TestPlayer;
    void buildTransport(QVBoxLayout *layout);
    void buildPlaylist(QWidget *parent);
    void updateChrome();
    void layoutChrome();
    bool overlayChrome_=false;
    void updatePlaylist();
    void populateFolder(QTreeWidgetItem *parent, const QString &path);
    void chooseFiles();
    void chooseFolder();
    void chooseBluRay();
    void chooseBluRayMode(const QString &path);
    bool openBluRay(const QString &path, bool menus = false);
    bool openDiscMenu(const QString &root, bool menus = true);
    QString discRoot_;
    std::unique_ptr<PlayerDiscMenu> discMenu_;
    QWidget *discSurface_=nullptr;
    bool discMenuNavigation_=false;
    QString discProgrammeKey_;
    QElapsedTimer discProgrammeSettling_;
    QHash<QString, QString> blurayLabels_;
    QJsonObject blurayMetadata_;
    QHash<QString,QJsonObject> blurayProgrammes_;
    bool handoffDiscProgramme();
    void applyBlurayMetadata();
    void chooseLink();
    void updateState();
    void requestFrame(int frame);
    void refreshScript();
    bool openMedia();
    bool networkSource() const;
    void savePosition();
    void suspendQualityCheck();
    void applyScaling();
    void setDirectMode(bool enabled);
    void ensureProfiles();
    QString profile() const;
    int fixedAnimeStage() const;
    int initialQualityStage() const;
    QStringList qualityNames() const;
    QStringList interpolationNames() const;
    int interpolationRenderer() const;
    bool advanceInterpolation();
    void showInterpolationWarning(bool visible);
    QSize profileTarget() const;
    void updateProfile();
    void setPlaylistPinned(bool pinned);
    void dockPlaylist();
    void showSettings();
    void showColorSettings();
    void applyColorSettings();
    void showSpeedPopup();
    void updateInfo();
    void nextFile(int direction);
    void setError(const QString &message);
    void showContextMenu(const QPoint &position);
    void showSubtitleStyle();
    void selectSubtitle(int slot, int stream);
    void attachSubtitle(const QString &path, int slot = 0);
    void attachAudio(const QString &path);
    void selectAudio(int stream);
    void applyAudioEffects();
    void showEqualizer();
    void matchExternalTracks();
    void loadAudioMetadata();
    void updateAudioLyrics(qint64 time);
    void useNativeAudio();
    void captureImage(bool source);
    void applySettings(bool reopen);
    void applyAppearance();
    bool madvrMode() const;
    int prefetchCount() const;
    void resetStatistics();
    bool commitFrameEdit();
    bool frameEditPending_ = false;
    int frameJumpTarget_ = -1;
    quint64 frameJumpPresents_ = 0;
    std::unique_ptr<QSettings> settings_;
    std::unique_ptr<PlayerSubtitles> subtitles_;
    std::unique_ptr<PlayerNetworkInput> network_;
    std::unique_ptr<PlayerLanguage> language_;
    std::unique_ptr<PlayerImage> imageLoader_;
    bool imageMode_ = false;
    bool audioMode_ = false, audioMetadataLoaded_ = false;
    PlayerAudioMetadata audioMetadata_;
    QLabel *lyricLabel_ = nullptr;
    QLabel *audioSubtitle_ = nullptr;
    QHash<QString,QString> blurayGroups_;
    QJsonArray externalSubtitleTracks_[2],externalChapters_;
    int externalSubtitleIndex_[2]{-1,-1};
    PlayerImageTools *imageTools_ = nullptr;
    PlayerResources resources_;
    ResourceUsage usage_;
    ThreeFpApi api_;
    std::unique_ptr<ThreeFpPlayer> clock_;
    std::unique_ptr<ThreeFpPlayer> output_;
    std::unique_ptr<VapourSynthFrameServer> server_;
    std::unique_ptr<LavPlayback> lav_;
    PreviewPane *pane_ = nullptr;
    QWidget *hidden_ = nullptr;
    QLabel *info_ = nullptr;
    QLabel *message_ = nullptr;
    QLabel *dragHint_ = nullptr;
    QLabel *interpolationWarning_ = nullptr;
    QLabel *videoBadge_ = nullptr;
    QLabel *audioBadge_ = nullptr;
    QPushButton *decoderBadge_ = nullptr;
    QLabel *hdrBadge_ = nullptr;
    QLabel *rendererBadge_ = nullptr;
    QSlider *timeline_ = nullptr;
    QSlider *volume_ = nullptr;
    QPushButton *mute_ = nullptr;
    QPushButton *play_ = nullptr;
    QPushButton *resetZoom_ = nullptr;
    QLineEdit *time_ = nullptr;
    QLineEdit *frame_ = nullptr;
    QLabel *duration_ = nullptr;
    QDoubleSpinBox *rate_ = nullptr;
    QTimer *timer_ = nullptr;
    QTimer *chromeTimer_ = nullptr;
    QWidget *controls_ = nullptr;
    QWidget *playlistPanel_ = nullptr;
    QSplitter *videoSplit_ = nullptr;
    bool playlistPinned_ = false;
    bool playlistDismissed_ = false;
    int playlistWidth_ = 320;
    int playlistExpansion_ = 0;
    QTreeWidget *playlist_ = nullptr;
    QString playlistDirectory_;
    QElapsedTimer chromeIdle_;
    QString source_;
    QString mediaInput_;
    bool direct_ = false;
    int qualityStage_ = 0;
    bool interpolationAuto_ = false;
    QSize profileSize_;
    QElapsedTimer qualityTimer_;
    QElapsedTimer qualitySettling_;
    QElapsedTimer profileStartup_;
    bool profileFallback_ = false;
    QElapsedTimer positionTimer_;
    bool positionRestored_ = false;
    quint64 qualityDropped_ = 0, qualitySubmitted_ = 0;
    qint64 resumeAt_ = -1;
    qint64 settingsPosition_ = -1;
    QTimer *profileResize_ = nullptr;
    QString preset_;
    QString deferred_;
    QString pendingMediaOpen_;
    QString deferredSubtitle_;
    int deferredSubtitleSlot_ = 0;
    QString deferredAudio_, pendingExternalAudio_;
    QStringList files_;
    int fileIndex_ = -1;
    VapourSynthClipInfo clip_;
    QJsonObject media_;
    bool ready_ = false;
    bool pending_ = false;
    bool playing_ = false;
    bool autoPlay_ = false;
    bool seekPending_ = false;
    qint64 seekUiTarget_ = -1, queuedSeek_ = -1;
    quint64 seekPresented_ = 0;
    QTimer *timelinePreview_ = nullptr;
    qint64 timelineTarget_ = -1;
    qint64 timelineSeekTarget_ = -1;
    quint64 timelinePresented_ = 0;
    bool timelineDragging_ = false, timelineResume_ = false, timelineWaiting_ = false;
    bool useLav_ = false;
    bool lavVideo_ = false;
    bool lavAudio_ = false;
    bool infoVisible_ = false;
    QElapsedTimer infoFpsTimer_;
    quint64 infoLastFrames_ = 0;
    double infoCurrentFps_ = 0;
    bool rateApplied_ = false;
    bool lavKeyPending_ = false;
    int manualFrame_ = -1;
    int requested_ = -1;
    int lastFrame_ = -1;
    int infoTick_ = 0;
    quint64 generation_ = 0;
    double speed_ = 1;
    QPointer<QWidget> speedPopup_;
    QPushButton *speedButton_ = nullptr;
    QByteArray normalGeometry_;
    quint64 skippedFrames_ = 0, submittedFrames_ = 0;
    QElapsedTimer frameTimer_;
    double frameMilliseconds_ = 0;
    VapourSynthFrame displayedFrame_;
    QString externalSubtitle_;
    QString externalSecondarySubtitle_;
    QString externalAudio_;
    bool matchedTracks_ = false;
    qint64 audioDelay_ = 0;
    QPointer<QWidget> equalizerWindow_;
    QString dragStatus_;
    int primarySubtitle_ = -1, secondarySubtitle_ = -1;
    bool subtitleVisible_ = true;
    int subtitleTick_ = 0;
};
}
